import test from "node:test"; import assert from "node:assert/strict"; import { readFile } from "node:fs/promises"; import { createWebApplication } from "../src/web/bootstrap.js"; import { buildExerciseSetRequest, createInitialExerciseSetState, transitionExerciseSetState } from "../src/web/exercise-set/workflow.js"; import { validateExerciseSetPresentation } from "../src/web/exercise-set/presentation.js";

test("worksheet state edits metadata and preserves stable identities through duplication and ordering", async () => { const runtime = await createWebApplication(); let state = createInitialExerciseSetState(runtime.catalogs); const firstSection = state.sections[0].id, firstItem = state.sections[0].items[0].id; state = transitionExerciseSetState(state,{type:"metadata",change:{title:"Studio Set",subtitle:"Week 1",instructions:"Play evenly."}},runtime.catalogs); state = transitionExerciseSetState(state,{type:"duplicate-item",sectionId:firstSection,itemId:firstItem},runtime.catalogs); const duplicate = state.sections[0].items[1].id; assert.notEqual(duplicate,firstItem); assert.notStrictEqual(state.sections[0].items[0].controls,state.sections[0].items[1].controls); state = transitionExerciseSetState(state,{type:"move-item-up",sectionId:firstSection,itemId:duplicate},runtime.catalogs); assert.deepEqual(state.sections[0].items.map(value=>value.id),[duplicate,firstItem]); state = transitionExerciseSetState(state,{type:"add-section"},runtime.catalogs); const second = state.sections[1].id; state = transitionExerciseSetState(state,{type:"move-section-up",sectionId:second},runtime.catalogs); assert.deepEqual(state.sections.map(value=>value.id),[second,firstSection]); assert.equal(Object.isFrozen(state),true); assert.equal(Object.isFrozen(state.sections),true); await runtime.dispose(); });

test("worksheet request builder supports all nine families through shared normalization", async () => { const runtime = await createWebApplication(); let state=createInitialExerciseSetState(runtime.catalogs), section=state.sections[0].id, current=state.sections[0].items[0].id; const families=["scale","scale-thirds","arpeggio-triad","arpeggio-seventh","chord-blocked","chord-broken","approach-note","enclosure","chord-progression"]; for(let index=0;index<families.length;index+=1){ if(index){ state=transitionExerciseSetState(state,{type:"add-item",sectionId:section},runtime.catalogs); current=state.sections[0].items.at(-1).id; } state=transitionExerciseSetState(state,{type:"edit-controls",sectionId:section,itemId:current,change:{type:families[index]}},runtime.catalogs); } const request=buildExerciseSetRequest(state,runtime.catalogs); assert.deepEqual(request.items.map(value=>String(value.application.exercise.type)),families); assert.equal(Object.isFrozen(request),true); assert.equal(Object.isFrozen(request.items),true); await runtime.dispose(); });

test("worksheet normalization retains extended foundational chords and rejects advanced target incompatibility", async () => { const runtime=await createWebApplication(); const extended=Object.freeze({id:"major-9",name:"Major Ninth",memberCount:5,targetCompatible:false}), catalogs=Object.freeze({...runtime.catalogs,chords:Object.freeze([...runtime.catalogs.chords,extended])}); let state=createInitialExerciseSetState(catalogs), section=state.sections[0].id,itemId=state.sections[0].items[0].id; state=transitionExerciseSetState(state,{type:"edit-controls",sectionId:section,itemId,change:{type:"chord-blocked"}},catalogs); state=transitionExerciseSetState(state,{type:"edit-controls",sectionId:section,itemId,change:{quality:"major-9"}},catalogs); assert.equal(buildExerciseSetRequest(state,catalogs).items[0].application.exercise.quality,"major-9"); state=transitionExerciseSetState(state,{type:"edit-controls",sectionId:section,itemId,change:{type:"approach-note"}},catalogs); assert.notEqual(state.sections[0].items[0].controls.quality,"major-9"); await runtime.dispose(); });

test("worksheet presentation validates each authoritative trusted SVG result", async () => { const runtime=await createWebApplication(), request=buildExerciseSetRequest(createInitialExerciseSetState(runtime.catalogs),runtime.catalogs), result=runtime.exerciseSetApplication.run(request); assert.strictEqual(validateExerciseSetPresentation(result),result.document); assert.match(result.document.items[0].presentation.rows[0].content,/^<svg/); await runtime.dispose(); });

test("worksheet browser source preserves Web-only boundaries and stable React keys", async () => { const source=await readFile(new URL("../src/web/exercise-set/ExerciseSetPanel.jsx",import.meta.url),"utf8"), core=await readFile(new URL("../src/core/ExerciseSet/ExerciseSetApplication.js",import.meta.url),"utf8"); assert.match(source,/key=\{section\.id\}/); assert.match(source,/key=\{item\.id\}/); assert.doesNotMatch(source,/key=\{(?:sectionIndex|itemIndex)\}/); assert.doesNotMatch(source,/Playback|Transport|AudioContext|MIDI|localStorage|fetch\(/); assert.doesNotMatch(core,/from ["']react|globalThis\.|window\.|AudioContext|navigator\.|setTimeout/i); });
