import test from "node:test"; import assert from "node:assert/strict"; import { spawnSync } from "node:child_process";
import { ExerciseSet, ExerciseSetApplication, ExerciseSetModule, ExerciseSetRequest, ExerciseSetResult, ExerciseSetWorkflowError, Kernel, NotationModule, RenderingModule, TheoryModule, ExerciseModule, ExerciseNotationModule, ExerciseApplicationModule, ValidationError } from "../src/core/index.js";

async function source({ set = true } = {}) { const kernel = new Kernel().use(new TheoryModule()).use(new NotationModule()).use(new RenderingModule()).use(new ExerciseModule()).use(new ExerciseNotationModule()).use(new ExerciseApplicationModule()); if (set) kernel.use(new ExerciseSetModule()); await kernel.start(); return kernel; }
const item = (exercise, options = {}) => ({ ...options, application: { exercise, rendering: { format: "svg" } } });

test("one-section sets preserve authoritative item result ownership and renderer identity", async () => { const kernel = await source(); const app = kernel.services.resolve("exercise.set.application"), result = app.run({ title: "Basics", sections: [{ title: "Scales", items: [item({ type: "scale", root: "Cb" })] }] }); assert.ok(result instanceof ExerciseSetResult); assert.strictEqual(result.document.items[0].result.request, result.request.items[0].application); assert.strictEqual(result.document.items[0].presentation, result.document.items[0].result.presentation); const row = result.document.items[0].presentation.rows[0]; assert.equal(row.rendererPluginId, "core.rendering.svg"); assert.equal(row.rendererStrategyId, "svg"); assert.equal(row.mediaType, "image/svg+xml"); assert.equal(String(row.graph.nodesOfType("note")[0].pitch), "Cb4"); await kernel.dispose(); });

test("heterogeneous sections retain caller order, spelling, progression, and target semantics", async () => { const kernel = await source(), app = kernel.services.resolve("exercise.set.application"); const result = app.run({ title: "Mixed", subtitle: "Exact", instructions: "In order", sections: [{ id: "first", title: "Foundations", items: [item({ type: "scale", root: "Cb" }, { id: "scale" }), item({ type: "chord-blocked", root: "B#", quality: "major" }, { id: "chord" })] }, { id: "advanced", title: "Advanced", items: [item({ type: "approach-note", root: "C", quality: "major", target: "third", approachPattern: "chromatic-below" }, { id: "approach" }), item({ type: "enclosure", root: "D", quality: "major", target: "fifth", enclosurePattern: "chromatic-above-below" }, { id: "enclosure" }), item({ type: "chord-progression", root: "C", progression: "ii-v-i-major" }, { id: "progression" })] }] }); assert.deepEqual(result.document.sections.map(value => value.id), ["first", "advanced"]); assert.deepEqual(result.document.items.map(value => value.id), ["scale", "chord", "approach", "enclosure", "progression"]); assert.equal(result.document.items[2].result.model.rows[0].metadata.target, "third"); assert.equal(result.document.items[3].result.model.rows[0].metadata.pattern, "chromatic-above-below"); assert.equal(result.document.items[4].result.model.rows[0].metadata.progressionId, "ii-v-i-major"); assert.equal(String(result.document.items[1].result.model.rows[0].root), "B#"); await kernel.dispose(); });

test("generated and caller identities are stable and equivalent requests/results compare deeply", async () => { const value = { title: "Stable", sections: [{ title: "One", items: [item({ type: "scale", root: "C" }), item({ type: "chord-broken", root: "D", quality: "minor" }, { id: "caller-item", label: "D minor" })] }] }, first = new ExerciseSetRequest(value), second = new ExerciseSetRequest(structuredClone(value)); assert.equal(first.identity, second.identity); assert.equal(first.sections[0].id, "section:1"); assert.equal(first.items[1].id, "caller-item"); assert.deepEqual(first, second); const kernel = await source(), app = kernel.services.resolve("exercise.set.application"); assert.deepEqual(app.run(first), app.run(second)); await kernel.dispose(); });

test("supplied ExerciseModel bypass remains exact through a set", async () => { const kernel = await source(), model = kernel.services.resolve("exercise.engine").generate({ type: "scale-thirds", root: "F#" }), result = kernel.services.resolve("exercise.set.application").run({ title: "Model", sections: [{ title: "Supplied", items: [{ application: { model } }] }] }); assert.strictEqual(result.document.items[0].result.model, model); assert.equal(result.document.items[0].result.metadata.generationBypassed, true); await kernel.dispose(); });

test("set validation rejects empty, duplicate, malformed, oversized, unknown, and nested invalid input with context", () => { const valid = item({ type: "scale", root: "C" }); for (const input of [{ title: "X", sections: [] }, { title: "X", sections: [{ title: "Empty", items: [] }] }, { title: " ", sections: [{ title: "A", items: [valid] }] }, { title: "X", extra: true, sections: [{ title: "A", items: [valid] }] }, { title: "X", sections: [{ id: "same", title: "A", items: [valid] }, { id: "same", title: "B", items: [valid] }] }, { title: "X", sections: [{ title: "A", items: [{ id: "same", ...valid }, { id: "same", ...valid }] }] }]) assert.throws(() => new ExerciseSetRequest(input), ValidationError); assert.throws(() => new ExerciseSetRequest({ title: "X", sections: [{ id: "context", title: "A", items: [item({ type: "unknown" })] }] }), /item 1.*section "context"/i); assert.throws(() => new ExerciseSetRequest({ title: "X", sections: Array.from({ length: 33 }, (_, index) => ({ title: `S${index}`, items: [valid] })) }), /at most 32/); });

test("all public set values and nested collections are deeply immutable without mutating sources", async () => { const input = { title: "Frozen", sections: [{ title: "A", items: [item({ type: "scale", root: "C" }, { label: "Scale" })] }] }, before = JSON.stringify(input), request = new ExerciseSetRequest(input), kernel = await source(), result = kernel.services.resolve("exercise.set.application").run(request); assert.equal(JSON.stringify(input), before); for (const value of [request, request.sections, request.sections[0], request.items, request.items[0], result, result.metadata, result.document, result.document.sections, result.document.items, result.document.sections[0], result.document.items[0]]) assert.equal(Object.isFrozen(value), true); assert.equal(result.metadata.atomic,true); await kernel.dispose(); });

test("set processing is sequential and failure is contextual and atomic", async () => { const base = await source({ set:false }), active = base.services.resolve("exercise.application.engine"), calls = [], cause = new Error("second failed"), application = new ExerciseSetApplication({ exerciseApplication: { run(request) { calls.push(request); if (calls.length === 2) throw cause; return active.run(request); } } }); assert.throws(() => application.run({ title: "Failure", sections: [{ id: "section-a", title: "A", items: [item({}), item({})] }] }), error => error instanceof ExerciseSetWorkflowError && error.sectionId === "section-a" && error.itemId.includes("item:2") && error.cause === cause); assert.equal(calls.length, 2); await base.dispose(); });

test("ExerciseSetModule resolves the active service and rebinds across reusable lifecycles", async () => { const base = await source({ set: false }), kernel = new Kernel(), first = base.services.resolve("exercise.application.engine"); kernel.services.register("exercise.application.engine", first); const module = new ExerciseSetModule(); module.configure(kernel.context); assert.strictEqual(module.application.exerciseApplication, first); const old = module.application; module.dispose(); module.dispose(); const replacement = { run() {} }; kernel.services.register("exercise.application.engine", replacement, { replace: true }); module.configure(kernel.context); assert.notStrictEqual(module.application, old); assert.strictEqual(module.application.exerciseApplication, replacement); module.dispose(); await base.dispose(); });

test("ExerciseSetModule collisions and listener failures roll back every owned insertion", async () => { const base = await source({ set: false }), exerciseApplication = base.services.resolve("exercise.application.engine"); const setup = () => { const kernel = new Kernel(); kernel.services.register("exercise.application.engine", exerciseApplication); return kernel; }; const points = [["container", (k,v) => k.services.register("exercise.set.application", v)], ["service", (k,v) => k.registries.services.register(ExerciseSet.serviceDescriptor, { value:v })], ["plugin", (k,v) => k.registries.plugins.register(ExerciseSet.pluginDescriptor, { value:v })], ["exercise", (k,v) => k.registries.exercises.register(ExerciseSet.workflowDescriptor, { value:v })]]; for (const [name, seed] of points) { const kernel = setup(), module = new ExerciseSetModule(), existing = { name }; seed(kernel, existing); assert.throws(() => module.configure(kernel.context)); assert.equal(kernel.services.resolve("exercise.set.application", { optional:true }), name === "container" ? existing : null); }
    for (const registryName of ["services","plugins","exercises"]) { const kernel = setup(), module = new ExerciseSetModule(); kernel.registries[registryName].subscribe(event => { if (event.type === "registered") throw new Error("listener"); }); assert.throws(() => module.configure(kernel.context), /listener/); assert.equal(kernel.services.has("exercise.set.application"), false); } await base.dispose(); });

test("same-object collisions, replacements, caller ownership, and public descriptors are preserved", async () => { const base = await source({ set:false }), injected = new ExerciseSetApplication({ exerciseApplication: base.services.resolve("exercise.application.engine") }); for (const point of ["container","service","plugin","exercise"]) { const kernel = new Kernel(), module = new ExerciseSetModule({ application: injected }); if (point === "container") kernel.services.register("exercise.set.application", injected); if (point === "service") kernel.registries.services.register(ExerciseSet.serviceDescriptor,{value:injected}); if (point === "plugin") kernel.registries.plugins.register(ExerciseSet.pluginDescriptor,{value:module.plugin}); if (point === "exercise") kernel.registries.exercises.register(ExerciseSet.workflowDescriptor,{value:injected}); assert.throws(() => module.configure(kernel.context)); }
    const replacements=[["container",(k,v)=>k.services.register("exercise.set.application",v,{replace:true}),k=>k.services.resolve("exercise.set.application")],["service",(k,v)=>k.registries.services.register(ExerciseSet.serviceDescriptor,{value:v,replace:true}),k=>k.registries.services.resolve("exercise.set.application")],["plugin",(k,v)=>k.registries.plugins.register(ExerciseSet.pluginDescriptor,{value:v,replace:true}),k=>k.registries.plugins.resolve("core.exercise-set.application")],["exercise",(k,v)=>k.registries.exercises.register(ExerciseSet.workflowDescriptor,{value:v,replace:true}),k=>k.registries.exercises.resolve("exercise.set.workflow")]]; for(const [name,replace,read] of replacements){const kernel=new Kernel(),module=new ExerciseSetModule({application:injected}),replacement={name};module.configure(kernel.context);replace(kernel,replacement);module.dispose();assert.strictEqual(read(kernel),replacement);}
    const kernel = new Kernel(), module = new ExerciseSetModule({ application: injected }), plugin = module.plugin; module.configure(kernel.context); module.dispose(); assert.strictEqual(module.application, injected); assert.strictEqual(module.plugin, plugin); assert.equal(String(ExerciseSet.descriptor.version), "8.6.0"); assert.equal(Object.isFrozen(ExerciseSet), true); await base.dispose(); });

test("Core ExerciseSet import and execution access no browser, audio, MIDI, or timer globals", () => { const script = `for (const name of ["window","document","AudioContext","navigator","MIDIInput","setTimeout"]) Object.defineProperty(globalThis,name,{configurable:true,get(){throw new Error("forbidden "+name)}}); const C=await import("./src/core/index.js"); const k=new C.Kernel().use(new C.TheoryModule()).use(new C.NotationModule()).use(new C.RenderingModule()).use(new C.ExerciseModule()).use(new C.ExerciseNotationModule()).use(new C.ExerciseApplicationModule()).use(new C.ExerciseSetModule()); await k.start(); const r=k.services.resolve("exercise.set.application").run({title:"Headless",sections:[{title:"A",items:[{application:{exercise:{type:"scale",root:"Cb"}}}]}]}); if(!r.document.items.length) throw new Error("missing");`; const child = spawnSync(process.execPath,["--input-type=module","--eval",script],{cwd:new URL("..",import.meta.url),encoding:"utf8"}); assert.equal(child.status,0,child.stderr||child.stdout); });
