import test from "node:test"; import assert from "node:assert/strict";
import { ChordNode, Clef, Duration, KeySignature, Layout, LayoutEngine, LayoutModule, LayoutRequest, LayoutStrategyRegistry, MeasureNode, NoteNode, PartNode, RestNode, ScoreEdge, ScoreGraph, ScoreGraphLayoutStrategy, ScoreRootNode, VoiceNode, Kernel, ValidationError } from "../src/core/index.js";

function score({ reverse=false, measures=3 }={}) { const nodes=[new ScoreRootNode({id:"layout-score",title:"Layout"}),new PartNode({id:"part",name:"Piano",clef:new Clef("treble")})],edges=[new ScoreEdge({from:"layout-score",to:"part",type:"contains"})];let previous=null;for(let m=1;m<=measures;m++){const measure=new MeasureNode({id:`measure:${m}`,number:m,beats:4,beatUnit:4,keySignature:new KeySignature({tonic:m===1?"Cb":"C",mode:"major"})}),voice=new VoiceNode({id:`voice:${m}`,index:1});nodes.push(measure,voice);edges.push(new ScoreEdge({from:"part",to:measure.id,type:"contains"}),new ScoreEdge({from:measure.id,to:voice.id,type:"contains"}));const quarter={numerator:1,denominator:4},eighth={numerator:1,denominator:8},values=m===2?[new ChordNode({id:`chord:${m}`,notes:["Cb4","Eb4","Gb4","Bb4"],duration:quarter,offset:1}),new RestNode({id:`rest:${m}`,duration:quarter,offset:2})]:[new NoteNode({id:`note:${m}:b`,pitch:m===1?"Cb4":"B#3",duration:eighth,offset:1}),new NoteNode({id:`note:${m}:a`,pitch:"F#4",duration:eighth,offset:1})];for(const event of values){nodes.push(event);edges.push(new ScoreEdge({from:voice.id,to:event.id,type:"contains"}));if(previous)edges.push(new ScoreEdge({from:previous,to:event.id,type:"next"}));previous=event.id;}}return new ScoreGraph({nodes:reverse?[...nodes].reverse():nodes,edges:reverse?[...edges].reverse():edges}); }
function engine(){const registry=new LayoutStrategyRegistry(),strategy=new ScoreGraphLayoutStrategy();registry.register(strategy.pluginId,strategy);return new LayoutEngine(registry);}

test("wide and narrow plans preserve event identity, ordering, spelling, timing, and atomic chords",()=>{const graph=score(),layout=engine(),wide=layout.plan({score:graph,availableWidth:1200}),narrow=layout.plan({score:graph,availableWidth:360,profile:"screen-compact"});assert.ok(narrow.systems.length>wide.systems.length);assert.deepEqual(wide.placements.map(v=>v.eventId),narrow.placements.map(v=>v.eventId));assert.equal(narrow.placements.filter(v=>v.eventId==="chord:2").length,1);assert.equal(String(graph.node("note:1:b").pitch),"Cb4");assert.equal(String(graph.node("note:3:b").pitch),"B#3");assert.equal(String(graph.node("chord:2").duration),"1/4");});
test("equivalent reversed graphs produce equivalent deterministic systems and placements",()=>{const a=engine().plan({score:score(),availableWidth:520}),b=engine().plan({score:score({reverse:true}),availableWidth:520});assert.deepEqual(a.systems.map(s=>({ids:s.measureIds,placements:s.measures.flatMap(m=>m.eventPlacements.map(p=>[p.eventId,p.x,p.y,p.order]))})),b.systems.map(s=>({ids:s.measureIds,placements:s.measures.flatMap(m=>m.eventPlacements.map(p=>[p.eventId,p.x,p.y,p.order]))})));});
test("mandatory semantic boundaries break while wrappable hints may share visual systems",()=>{const graph=score(),layout=engine(),mandatory=layout.plan({score:graph,availableWidth:1200,semanticSystems:[{id:"a",measureIds:["measure:1"],breakPolicy:"wrappable"},{id:"b",measureIds:["measure:2","measure:3"],breakPolicy:"mandatory"}]}),wrappable=layout.plan({score:graph,availableWidth:1200,semanticSystems:[{id:"a",measureIds:["measure:1"],breakPolicy:"wrappable"},{id:"b",measureIds:["measure:2","measure:3"],breakPolicy:"wrappable"}]});assert.equal(mandatory.systems.length,2);assert.equal(wrappable.systems.length,1);});
test("exact-fit and one-unit-under widths have deterministic boundary behavior",()=>{const graph=score({measures:1}),layout=engine(),base=layout.plan({score:graph,availableWidth:1200}),required=base.systems[0].naturalWidth,exact=layout.plan({score:graph,availableWidth:required}),under=layout.plan({score:graph,availableWidth:required-1});assert.equal(exact.systems[0].overflow,false);assert.equal(under.systems[0].overflow,true);assert.equal(under.systems[0].naturalWidth,exact.systems[0].naturalWidth);});
test("oversized measures retain natural width and reject unsafe requests and hints",()=>{const graph=score({measures:1}),layout=engine(),plan=layout.plan({score:graph,availableWidth:160});assert.equal(plan.systems[0].overflow,true);assert.ok(plan.bounds.width>160);for(const request of [{score:graph,availableWidth:0},{score:graph,availableWidth:Infinity},{score:graph,availableWidth:10100},{score:graph,availableWidth:400,horizontalPadding:-1},{score:graph,availableWidth:400,semanticSystems:[{id:"x",measureIds:["missing"]}]}])assert.throws(()=>layout.plan(request),ValidationError);});
test("profiles, requests, plans, bounds, systems, measures, placements, metadata, and source remain immutable",()=>{const graph=score(),before=JSON.stringify(graph),request=new LayoutRequest({score:graph,availableWidth:600,profile:"print-worksheet"}),plan=engine().plan(request);for(const value of [Layout,Layout.layoutProfiles,request,request.profile,request.semanticSystems,plan,plan.systems,plan.bounds,plan.metadata,plan.systems[0],plan.systems[0].measures[0],plan.placements[0]])assert.equal(Object.isFrozen(value),true);assert.equal(JSON.stringify(graph),before);});
test("registry selection is deterministic, explicit, isolated, replaceable, and removable",()=>{const graph=score(),request=new LayoutRequest({score:graph,availableWidth:600}),registry=new LayoutStrategyRegistry(),z=new ScoreGraphLayoutStrategy({pluginId:"z.layout"}),a=new ScoreGraphLayoutStrategy({pluginId:"a.layout"});registry.register(z.pluginId,z);registry.register(a.pluginId,a);assert.strictEqual(registry.select(request),a);const explicit=new LayoutRequest({score:graph,availableWidth:600,pluginId:"z.layout",strategyId:"score-graph"});assert.strictEqual(registry.select(explicit),z);const replacement=new ScoreGraphLayoutStrategy({pluginId:"z.layout"});registry.register("z.layout",replacement,{replace:true});assert.strictEqual(registry.get("z.layout","score-graph"),replacement);assert.equal(registry.unregister("z.layout","score-graph"),true);});
test("LayoutEngine rejects strategy output whose authoritative identity metadata is incompatible",()=>{class InvalidStrategy extends Layout.LayoutStrategy{constructor(){super({id:"invalid",pluginId:"test.layout"});}supports(){return true;}layout(request){return engine().plan(request);}}const registry=new LayoutStrategyRegistry(),strategy=new InvalidStrategy();registry.register(strategy.pluginId,strategy);assert.throws(()=>new LayoutEngine(registry).plan({score:score(),availableWidth:600}),/strategy metadata/);});
test("LayoutModule registration is transactional, reusable, and public",async()=>{const kernel=new Kernel(),module=new LayoutModule();module.configure(kernel.context);assert.strictEqual(kernel.services.resolve("layout.engine"),module.engine);assert.equal(String(Layout.descriptor.version),"8.8.0");module.dispose();module.configure(kernel.context);assert.strictEqual(kernel.services.resolve("layout.engine"),module.engine);module.dispose();});

test("LayoutModule preserves every collision and rolls back earlier registrations",()=>{const cases=[
    {area:"container",id:"layout.engine",value:module=>module.engine},
    {area:"container",id:"layout.strategyRegistry",value:module=>module.strategyRegistry},
    {area:"services",descriptor:Layout.serviceDescriptors.engine,value:module=>module.engine},
    {area:"services",descriptor:Layout.serviceDescriptors.strategies,value:module=>module.strategyRegistry},
    {area:"plugins",descriptor:Layout.pluginDescriptor,value:module=>module.plugin}
];for(const scenario of cases){const kernel=new Kernel(),module=new LayoutModule(),value=scenario.value(module),unrelated=Object.freeze({unrelated:true});kernel.services.register("unrelated",unrelated);let record=null;if(scenario.area==="container")kernel.services.register(scenario.id,value);else record=kernel.registries[scenario.area].register(scenario.descriptor,{value});assert.throws(()=>module.configure(kernel.context),/already registered|Duplicate registration/);assert.strictEqual(kernel.services.resolve("unrelated"),unrelated);if(scenario.area==="container")assert.strictEqual(kernel.services.resolve(scenario.id),value);else assert.strictEqual(kernel.registries[scenario.area].getRecord(scenario.descriptor.id),record);for(const id of ["layout.engine","layout.strategyRegistry"])assert.equal(kernel.services.has(id),scenario.area==="container"&&scenario.id===id);assert.equal(kernel.registries.services.size,scenario.area==="services"?1:0);assert.equal(kernel.registries.plugins.size,scenario.area==="plugins"?1:0);assert.strictEqual(module.strategyRegistry.get(module.strategy.pluginId,module.strategy.id),module.strategy);module.dispose();}});

test("LayoutModule rolls back listener failures and preserves post-configuration replacements",()=>{const failedKernel=new Kernel(),failed=new LayoutModule();failedKernel.registries.plugins.subscribe(event=>{if(event.type==="registered"&&String(event.record.id)==="core.layout.score-graph")throw new Error("listener failed");});assert.throws(()=>failed.configure(failedKernel.context),/listener failed/);assert.equal(failedKernel.services.has("layout.engine"),false);assert.equal(failedKernel.services.has("layout.strategyRegistry"),false);assert.equal(failedKernel.registries.services.size,0);assert.equal(failedKernel.registries.plugins.size,0);
    const kernel=new Kernel(),module=new LayoutModule();module.configure(kernel.context);const replacementEngine=Object.freeze({replacement:true}),replacementPlugin=Object.freeze({replacement:true});kernel.services.register("layout.engine",replacementEngine,{replace:true});kernel.registries.plugins.register(Layout.pluginDescriptor,{value:replacementPlugin,replace:true});module.dispose();module.dispose();assert.strictEqual(kernel.services.resolve("layout.engine"),replacementEngine);assert.strictEqual(kernel.registries.plugins.resolve(Layout.pluginDescriptor.id),replacementPlugin);assert.equal(kernel.services.has("layout.strategyRegistry"),false);assert.equal(kernel.registries.services.size,0);const fresh=new Kernel();module.configure(fresh.context);assert.strictEqual(fresh.services.resolve("layout.engine"),module.engine);module.dispose();});
