import test from"node:test";import assert from"node:assert/strict";import{spawnSync}from"node:child_process";
import{ExportModule,ExerciseApplicationModule,ExerciseModule,ExerciseNotationModule,ExerciseSetModule,HtmlPublishingStrategy,Kernel,LayoutModule,NotationModule,PAGE_PROFILES,PageProfile,PdfPublishingStrategy,PublicationBlock,PublishingEngine,PublishingModule,PublishingRequest,PublishingStrategyRegistry,RenderingModule,SvgPublishingStrategy,TheoryModule,ValidationError}from"../src/core/index.js";
async function fixture(){const layout=new LayoutModule(),kernel=new Kernel().use(new TheoryModule()).use(new NotationModule()).use(layout).use(new RenderingModule({layoutEngine:layout.engine})).use(new ExerciseModule()).use(new ExerciseNotationModule()).use(new ExerciseApplicationModule()).use(new ExerciseSetModule()).use(new ExportModule()).use(new PublishingModule());await kernel.start();const source=kernel.services.resolve("exercise.set.application").run({title:"Exact & readable",subtitle:"Cb, B# and harmony",instructions:"Play <slowly> & name every note.",sections:[{title:"Foundations",items:[{id:"cb-scale",label:"C-flat major",application:{exercise:{type:"scale",root:"Cb"},rendering:{format:"svg"}}},{id:"dense-chord",label:"Dense chord",application:{exercise:{type:"chord-blocked",root:"B#",quality:"major"},rendering:{format:"svg"}}}]}]});return{kernel,source,engine:kernel.services.resolve("publishing.engine")};}
test("page profiles use exact immutable hundredths-of-point dimensions",()=>{assert.deepEqual(Object.keys(PAGE_PROFILES),["letter-portrait","letter-landscape","a4-portrait","a4-landscape"]);for(const value of Object.values(PAGE_PROFILES)){assert.equal(Object.isFrozen(value),true);assert.ok(value.contentBounds.width>0);}assert.throws(()=>new PageProfile({width:100,height:100}),ValidationError);assert.throws(()=>new PageProfile({width:61200,height:79200,margins:{left:40000,right:40000}}),ValidationError);});
test("publishing plans authoritative results without mutation and keeps headings with notation",async()=>{const{kernel,source,engine}=await fixture(),before=source.document.items[0].presentation.rows[0].content,result=engine.publish({source,format:"html",pageProfile:"letter-portrait"});assert.equal(result.plan.request.source,source);assert.equal(source.document.items[0].presentation.rows[0].content,before);assert.equal(Object.isFrozen(result.plan.pages),true);assert.ok(result.plan.pages.every(page=>page.blocks.every(block=>block.y+block.height<=page.profile.height-page.profile.margins.bottom)));const types=result.plan.blocks.map(value=>value.type);assert.ok(types.includes("item-heading")&&types.includes("notation"));await kernel.dispose();});
test("HTML output is semantic, escaped, self-contained, and embeds trusted SVG only",async()=>{const{kernel,source,engine}=await fixture(),result=engine.publish({source,format:"html",title:"A < B & C"}),html=result.document.assets[0].content;assert.match(html,/<!doctype html>/);assert.match(html,/A &lt; B &amp; C/);assert.doesNotMatch(html,/<script/i);assert.match(html,/@page/);assert.match(html,/<svg/);await kernel.dispose();});
test("SVG publishing emits one accessible explicitly and physically sized asset per page",async()=>{const{kernel,source,engine}=await fixture(),result=engine.publish({source,format:"svg",pageProfile:"a4-landscape"});assert.equal(result.document.assets.length,result.plan.pageCount);for(const asset of result.document.assets){assert.match(asset.content,/role="img"/);assert.match(asset.content,/aria-labelledby=/);assert.match(asset.content,/width="841\.89pt" height="595\.28pt" viewBox="0 0 84189 59528"/);assert.match(asset.filename,/\.svg$/);}await kernel.dispose();});
test("PDF output has deterministic bytes, page count, dimensions, and no timestamps",async()=>{const{kernel,source,engine}=await fixture(),input={source,format:"pdf",pageProfile:"letter-portrait",author:"Framework"},a=engine.publish(input),b=engine.publish(input),bytes=a.document.assets[0].content,text=new TextDecoder("latin1").decode(bytes);assert.deepEqual(bytes,b.document.assets[0].content);assert.equal(text.slice(0,8),"%PDF-1.7");assert.match(text,new RegExp(`/Count ${a.plan.pageCount}`));assert.match(text,/\/MediaBox \[0 0 612 792\]/);assert.doesNotMatch(text,/CreationDate|ModDate/);await kernel.dispose();});
test("requests validate formats, metadata, safe filenames, and authoritative sources",async()=>{const{kernel,source}=await fixture();assert.throws(()=>new PublishingRequest({source:{},format:"html"}),/authoritative/);assert.throws(()=>new PublishingRequest({source,format:"zip"}),/Unsupported/);assert.throws(()=>new PublishingRequest({source,filenameBase:"../"}),/unsafe/);const request=new PublishingRequest({source,format:"html",filenameBase:"My worksheet"});assert.equal(request.filenameBase,"My-worksheet");assert.equal(Object.isFrozen(request),true);await kernel.dispose();});
test("publishing strategies remain plugin isolated and explicit",async()=>{const registry=new PublishingStrategyRegistry(),html=new HtmlPublishingStrategy({pluginId:"a"}),other=new HtmlPublishingStrategy({pluginId:"b"});registry.register("b",other);registry.register("a",html);assert.equal(registry.get("a","html"),html);assert.deepEqual(registry.strategies("b"),[other]);assert.throws(()=>registry.register("a",new HtmlPublishingStrategy({pluginId:"a"})),/already/);});
test("module registers transactionally and is reusable",async()=>{const layout=new LayoutModule(),module=new PublishingModule(),kernel=new Kernel().use(new TheoryModule()).use(new NotationModule()).use(layout).use(new RenderingModule({layoutEngine:layout.engine})).use(new ExerciseModule()).use(new ExerciseNotationModule()).use(new ExerciseApplicationModule()).use(new ExerciseSetModule()).use(new ExportModule()).use(module);await kernel.start();assert.ok(kernel.services.resolve("publishing.engine")instanceof PublishingEngine);await kernel.dispose();assert.equal(module.engine,null);});
test("public publication values reject clipping and remain deeply immutable",()=>{assert.throws(()=>new PublicationBlock({id:"x",type:"unknown",x:0,y:0,width:1,height:1}),ValidationError);for(const Strategy of[HtmlPublishingStrategy,SvgPublishingStrategy,PdfPublishingStrategy])assert.equal(Object.isFrozen(new Strategy()),true);});
test("Core Publishing imports without browser, filesystem, audio, MIDI, or clock globals",()=>{const script=`for(const name of ["window","document","navigator","AudioContext","MIDIInput","setTimeout","fetch"])Object.defineProperty(globalThis,name,{configurable:true,get(){throw new Error("forbidden "+name)}});const C=await import("./src/core/index.js");if(!C.PublishingEngine||!C.PAGE_PROFILES)throw new Error("missing Publishing");`;const child=spawnSync(process.execPath,["--input-type=module","--eval",script],{cwd:new URL("..",import.meta.url),encoding:"utf8"});assert.equal(child.status,0,child.stderr||child.stdout);});
