import { Identifier, ValidationError } from "../Foundation/index.js";
import { PublishingStrategy } from "./PublishingStrategy.js";
export class PublishingStrategyRegistry {
    #plugins=new Map();
    register(pluginId,strategy,{replace=false}={}){if(!(strategy instanceof PublishingStrategy))throw new ValidationError("Publishing strategy must extend PublishingStrategy.");const owner=String(Identifier.from(pluginId));if(String(strategy.pluginId)!==owner)throw new ValidationError(`Publishing strategy "${strategy.id}" belongs to another plugin.`);const values=this.#plugins.get(owner)??new Map(),key=String(strategy.id),previous=values.get(key);if(previous&&!replace){if(previous===strategy)return strategy;throw new ValidationError(`Publishing strategy "${key}" is already registered for plugin "${owner}".`);}values.set(key,strategy);this.#plugins.set(owner,values);return strategy;}
    get(pluginId,strategyId,{required=false}={}){const value=this.#plugins.get(String(pluginId))?.get(String(strategyId))??null;if(!value&&required)throw new ValidationError(`Publishing strategy "${strategyId}" was not found for plugin "${pluginId}".`);return value;}
    select(plan,{pluginId=null,strategyId=null}={}){if(strategyId&&!pluginId)throw new ValidationError("Explicit publishing strategy selection requires pluginId.");if(strategyId){const value=this.get(pluginId,strategyId,{required:true});if(value.format!==plan.request.format||!value.supports(plan))throw new ValidationError(`Publishing strategy "${strategyId}" is incompatible with this request.`);return value;}const values=[...this.#plugins].sort(([a],[b])=>a.localeCompare(b)).flatMap(([,entries])=>[...entries.values()].sort((a,b)=>String(a.id).localeCompare(String(b.id))));return values.find(value=>(!pluginId||String(value.pluginId)===String(pluginId))&&value.format===plan.request.format&&value.supports(plan))??null;}
    unregister(pluginId,strategyId){const values=this.#plugins.get(String(pluginId));if(!values)return false;const removed=values.delete(String(strategyId));if(!values.size)this.#plugins.delete(String(pluginId));return removed;}
    strategies(pluginId){return Object.freeze([...(this.#plugins.get(String(pluginId))?.values()??[])].sort((a,b)=>String(a.id).localeCompare(String(b.id))));}
}
