import { ValidationError } from "../Foundation/index.js";
import { PublishingEngine } from "./PublishingEngine.js";
import { PublishingStrategyRegistry } from "./PublishingStrategyRegistry.js";
import { HtmlPublishingStrategy, PdfPublishingStrategy, SvgPublishingStrategy } from "./strategies/index.js";
import { publishingPluginDescriptor, publishingServiceDescriptors } from "./descriptors.js";
import { publishingPackageDescriptor } from "./package.descriptor.js";
const undoAll=actions=>{const errors=[];for(const action of [...actions].reverse())try{action();}catch(error){errors.push(error);}return errors;};
export class PublishingModule{
    #configured=false;#undo=[];#injectedRegistry;#injectedEngine;
    constructor({registry=null,engine=null,strategies=null}={}){this.id=String(publishingPackageDescriptor.id);this.descriptor=publishingPackageDescriptor;this.#injectedRegistry=registry;this.#injectedEngine=engine;this.registry=registry;this.engine=engine;this.strategies=strategies??[new HtmlPublishingStrategy(),new SvgPublishingStrategy(),new PdfPublishingStrategy()];this.plugin=null;Object.seal(this);}
    configure({services,registries}){if(this.#configured)return this;for(const id of ["layout.engine","rendering.engine","export.engine","exercise.set.application"])if(!services.resolve(id,{optional:true}))throw new ValidationError(`PublishingModule requires active service "${id}".`);const registry=this.#injectedRegistry??new PublishingStrategyRegistry(),engine=this.#injectedEngine??new PublishingEngine({registry}),plugin=Object.freeze({id:String(publishingPluginDescriptor.id),strategies:Object.freeze([...this.strategies])}),undo=[];const service=(id,value)=>{services.register(id,value);undo.push(()=>{if(services.resolve(id,{optional:true})===value)services.unregister(id);});};const record=(descriptor,value)=>{const previous=registries.services.getRecord(descriptor.id);let inserted=null;const remove=current=>{if(registries.services.getRecord(descriptor.id)===current)registries.services.unregister(descriptor.id);};try{inserted=registries.services.register(descriptor,{value});}catch(error){const current=registries.services.getRecord(descriptor.id);if(!previous&&current?.descriptor===descriptor&&current?.value===value)try{remove(current);}catch{}throw error;}undo.push(()=>remove(inserted));};const pluginRecord=()=>{const previous=registries.plugins.getRecord(publishingPluginDescriptor.id);let inserted=null;const remove=current=>{if(registries.plugins.getRecord(publishingPluginDescriptor.id)===current)registries.plugins.unregister(publishingPluginDescriptor.id);};try{inserted=registries.plugins.register(publishingPluginDescriptor,{value:plugin});}catch(error){const current=registries.plugins.getRecord(publishingPluginDescriptor.id);if(!previous&&current?.descriptor===publishingPluginDescriptor&&current?.value===plugin)try{remove(current);}catch{}throw error;}undo.push(()=>remove(inserted));};
        try{for(const strategy of this.strategies){const existing=registry.get(strategy.pluginId,strategy.id);if(existing&&existing!==strategy)throw new ValidationError(`Built-in publishing strategy collision: "${strategy.id}".`);if(!existing){registry.register(strategy.pluginId,strategy);undo.push(()=>{if(registry.get(strategy.pluginId,strategy.id)===strategy)registry.unregister(strategy.pluginId,strategy.id);});}}service("publishing.strategy-registry",registry);service("publishing.engine",engine);record(publishingServiceDescriptors.strategies,registry);record(publishingServiceDescriptors.engine,engine);pluginRecord();this.registry=registry;this.engine=engine;this.plugin=plugin;this.#undo=undo;this.#configured=true;return this;}catch(error){const failures=undoAll(undo);if(failures.length)throw new AggregateError([error,...failures],"PublishingModule configuration and rollback failed.",{cause:error});throw error;}}
    dispose(){const errors=undoAll(this.#undo);this.#undo=[];this.#configured=false;if(!this.#injectedRegistry)this.registry=null;if(!this.#injectedEngine)this.engine=null;this.plugin=null;if(errors.length)throw new AggregateError(errors,"PublishingModule disposal failed.");return this;}
}
export default PublishingModule;
