import { ValidationError } from "../Foundation/index.js"; import { ExerciseSetApplication } from "./ExerciseSetApplication.js"; import { exerciseSetPluginDescriptor, exerciseSetServiceDescriptor, exerciseSetWorkflowDescriptor } from "./descriptors.js"; import { exerciseSetPackageDescriptor } from "./package.descriptor.js";
function undoAll(actions) { const errors = []; for (const action of [...actions].reverse()) try { action(); } catch (error) { errors.push(error); } return errors; }
export class ExerciseSetModule {
    #configured = false; #undo = []; #injected;
    constructor({ application = null } = {}) { this.id = String(exerciseSetPackageDescriptor.id); this.descriptor = exerciseSetPackageDescriptor; this.#injected = application; this.application = application; this.plugin = application ? this.#plugin(application) : null; Object.seal(this); }
    configure({ services, registries }) { if (this.#configured) return this; let application; try { application = this.#injected ?? new ExerciseSetApplication({ exerciseApplication: services.resolve("exercise.application.engine") }); } catch (cause) { throw new ValidationError("ExerciseSetModule requires the active exercise.application.engine service.", { cause }); } if (!application || typeof application.run !== "function") throw new ValidationError("ExerciseSetModule application must implement run()."); const plugin = this.#injected ? this.plugin : this.#plugin(application), undo = [];
        const service = (id, value) => { services.register(id, value); undo.push(() => { if (services.resolve(id, { optional: true }) === value) services.unregister(id); }); };
        const record = (registry, descriptor, value) => { const previous = registry.getRecord(descriptor.id); let inserted = null; const remove = current => { if (registry.getRecord(descriptor.id) === current) registry.unregister(descriptor.id); }; try { inserted = registry.register(descriptor, { value }); } catch (error) { const current = registry.getRecord(descriptor.id); if (!previous && current?.descriptor === descriptor && current?.value === value) try { remove(current); } catch {} throw error; } undo.push(() => remove(inserted)); };
        try { service("exercise.set.application", application); record(registries.services, exerciseSetServiceDescriptor, application); record(registries.plugins, exerciseSetPluginDescriptor, plugin); record(registries.exercises, exerciseSetWorkflowDescriptor, application); this.application = application; this.plugin = plugin; this.#undo = undo; this.#configured = true; return this; } catch (error) { const failures = undoAll(undo); if (failures.length) throw new AggregateError([error, ...failures], "ExerciseSetModule configuration and rollback failed.", { cause: error }); throw error; }
    }
    dispose() { const errors = undoAll(this.#undo); this.#undo = []; this.#configured = false; if (!this.#injected) { this.application = null; this.plugin = null; } if (errors.length) throw new AggregateError(errors, "ExerciseSetModule disposal failed."); return this; }
    #plugin(application) { return Object.freeze({ id: String(exerciseSetPluginDescriptor.id), workflows: Object.freeze([application]) }); }
}
export default ExerciseSetModule;
