import { ScoreGraph } from "../../Notation/index.js";
import { LayoutPlan } from "../../Layout/index.js";
import { LayoutEngine, LayoutStrategyRegistry, ScoreGraphLayoutStrategy } from "../../Layout/index.js";
import { ValidationError } from "../../Foundation/index.js";
import { RendererStrategy } from "./RendererStrategy.js";
import { metadataText, xmlAttribute, xmlText } from "./svg.js";

function node(score,id){const value=score.node(id);if(!value)throw new ValidationError(`Layout references unknown score node "${id}".`);return value;}
function metadataAttribute(value){return ` data-metadata="${xmlAttribute(metadataText(value.metadata))}"`;}
function renderEvent(score,placement){const event=node(score,placement.eventId),common=`class="event ${event.type}" data-node-id="${xmlAttribute(event.id)}" data-order="${placement.order}" data-offset="${event.offset}" data-duration="${xmlAttribute(event.duration)}" transform="translate(${placement.x} ${placement.y})"${metadataAttribute(event)}`;if(String(event.type)==="rest")return `<g ${common}><rect x="0" y="-8" width="18" height="8"/><text x="9" y="18" text-anchor="middle">rest</text></g>`;if(String(event.type)==="chord"){const spelling=event.notes.map(String).join(" ");return `<g ${common} data-pitches="${xmlAttribute(spelling)}"><circle cx="9" cy="0" r="8"/><text x="9" y="22" text-anchor="middle">${xmlText(spelling)}</text></g>`;}return `<g ${common} data-pitch="${xmlAttribute(event.pitch)}"><circle cx="9" cy="0" r="6"/><text x="9" y="22" text-anchor="middle">${xmlText(event.pitch)}</text></g>`;}
function renderMeasure(score,layoutMeasure,system){const measure=node(score,layoutMeasure.id),key=measure.keySignature,part=node(score,system.partId),signature=`${part.clef.type} clef, ${key?`${key.tonic} ${key.mode}`:"no key signature"}, ${measure.value.beats}/${measure.value.beatUnit}`,byVoice=new Map();for(const placement of layoutMeasure.eventPlacements){const list=byVoice.get(placement.voiceId)??[];list.push(placement);byVoice.set(placement.voiceId,list);}const voiceIds=new Set(score.edges.filter(edge=>String(edge.type)==="contains"&&String(edge.from)===String(measure.id)).map(edge=>String(edge.to))),voices=score.nodes.filter(value=>voiceIds.has(String(value.id))&&String(value.type)==="voice").sort((a,b)=>a.index-b.index||String(a.id).localeCompare(String(b.id))).map(voice=>`<g class="voice" data-node-id="${xmlAttribute(voice.id)}" data-index="${voice.index}"${metadataAttribute(voice)}>${(byVoice.get(String(voice.id))??[]).map(value=>renderEvent(score,value)).join("")}</g>`).join("");return `<g class="measure" data-node-id="${xmlAttribute(measure.id)}" data-number="${measure.number}" data-beats="${measure.value.beats}" data-beat-unit="${measure.value.beatUnit}" data-key-tonic="${xmlAttribute(key?.tonic??"")}" data-key-mode="${xmlAttribute(key?.mode??"none")}" data-key-accidentals="${key?.accidentals??0}" data-layout-width="${layoutMeasure.width}" data-overflow="${layoutMeasure.overflow}"${metadataAttribute(measure)}><rect x="${layoutMeasure.x}" y="${system.y}" width="${layoutMeasure.width}" height="${system.height}" fill="none" stroke="currentColor"/><text class="signature" x="${layoutMeasure.x+12}" y="${system.y+25}">${xmlText(signature)}</text>${voices}</g>`;}
function renderSystem(score,system){const part=node(score,system.partId),clef=part.clef;return `<g class="part layout-system" data-layout-system-id="${xmlAttribute(system.id)}" data-node-id="${xmlAttribute(part.id)}" data-name="${xmlAttribute(part.name)}" data-instrument="${xmlAttribute(part.instrument)}" data-clef="${xmlAttribute(clef.type)}" data-clef-line="${clef.line}" data-clef-octave-shift="${clef.octaveShift}" data-overflow="${system.overflow}"${metadataAttribute(part)}><text class="part-name" x="40" y="${system.y+20}">${xmlText(part.name)}</text>${system.measures.map(measure=>renderMeasure(score,measure,system)).join("")}</g>`;}
function defaultPlan(score,options){const registry=new LayoutStrategyRegistry(),strategy=new ScoreGraphLayoutStrategy();registry.register(strategy.pluginId,strategy);return new LayoutEngine(registry).plan({score,availableWidth:options.width,profile:options.layoutProfile,horizontalPadding:options.horizontalPadding,minimumSystemWidth:options.minimumSystemWidth,staffSpacing:options.staffSpacing,systemSpacing:options.systemSpacing,semanticSystems:options.semanticSystems});}
export class SvgScoreRenderer extends RendererStrategy{constructor({pluginId="core.rendering.svg"}={}){super({id:"svg",pluginId,format:"svg"});}supports(score){return score instanceof ScoreGraph;}render(score,options={}){const plan=options.layoutPlan??defaultPlan(score,options);if(!(plan instanceof LayoutPlan)||plan.score!==score)throw new ValidationError("SvgScoreRenderer requires an authoritative LayoutPlan for its ScoreGraph.");const width=plan.bounds.width,height=Number(options.height??Math.max(240,plan.bounds.height+50));if(!Number.isFinite(height)||height<=0)throw new ValidationError("SVG height must be a positive finite number.");const title=options.title??score.score.title,metadata=options.metadata??score.score.metadata,content=plan.systems.map(system=>renderSystem(score,system)).join("");return `<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="score-title" data-layout-profile="${xmlAttribute(plan.metadata.profileId)}" data-available-width="${plan.metadata.availableWidth}" data-natural-width="${plan.metadata.naturalWidth}" data-layout-metadata="${xmlAttribute(metadataText(plan.metadata))}"><title id="score-title">${xmlText(title)}</title><metadata>${xmlText(metadataText(metadata))}</metadata><g class="score" data-node-id="${xmlAttribute(score.score.id)}"${metadataAttribute(score.score)}><text class="score-title" x="40" y="35">${xmlText(title)}</text>${content}</g></svg>`;}}
export default SvgScoreRenderer;
