import { ValidationError } from "../Foundation/index.js";
import { LayoutRequest } from "./LayoutRequest.js";
import { LayoutStrategy } from "./LayoutStrategy.js";
import { LayoutBounds, LayoutEventPlacement, LayoutMeasure, LayoutMetadata, LayoutPlan, LayoutSystem } from "./values.js";

const eventTypes = new Set(["note","rest","chord"]);
function children(score,parent,type){const ids=new Set(score.edges.filter(edge=>String(edge.type)==="contains"&&String(edge.from)===String(parent.id)).map(edge=>String(edge.to)));return score.nodes.filter(node=>ids.has(String(node.id))&&(!type||String(node.type)===type));}
function idCompare(a,b){return String(a.id).localeCompare(String(b.id));}
function events(score,voice){const values=children(score,voice).filter(node=>eventTypes.has(String(node.type))),ids=new Set(values.map(v=>String(v.id))),next=new Map(values.map(v=>[String(v.id),[]])),indegree=new Map(values.map(v=>[String(v.id),0]));for(const edge of score.edges){if(String(edge.type)!=="next"||!ids.has(String(edge.from))||!ids.has(String(edge.to)))continue;next.get(String(edge.from)).push(String(edge.to));indegree.set(String(edge.to),indegree.get(String(edge.to))+1);}const compare=(a,b)=>a.offset-b.offset||idCompare(a,b),available=values.filter(v=>indegree.get(String(v.id))===0).sort(compare),ordered=[];while(available.length){const value=available.shift();ordered.push(value);for(const target of next.get(String(value.id)).sort()){const remaining=indegree.get(target)-1;indegree.set(target,remaining);if(!remaining){available.push(score.node(target));available.sort(compare);}}}if(ordered.length!==values.length)throw new ValidationError("Layout event precedence contains a cycle.");return ordered;}
function accidentalCount(value){return (String(value).match(/[#bx♯♭]/g)??[]).length;}
function eventWidth(event){if(String(event.type)==="rest")return 34;if(String(event.type)==="chord")return 48+event.notes.length*8+Math.max(...event.notes.map(accidentalCount))*14;return 38+accidentalCount(event.pitch)*14;}
function semanticIds(request,measureId){return request.semanticSystems.filter(system=>system.measureIds.includes(measureId)).map(system=>system.id);}

export class ScoreGraphLayoutStrategy extends LayoutStrategy {
    constructor({pluginId="core.layout.score-graph"}={}){super({id:"score-graph",pluginId});}
    supports(request){return request instanceof LayoutRequest;}
    layout(input){const request=LayoutRequest.from(input),score=request.score,profile=request.profile,contentWidth=request.availableWidth-request.horizontalPadding*2,parts=score.nodesOfType("part").sort(idCompare),systems=[];let globalSequence=0,y=request.horizontalPadding;
        for(const part of parts){const measures=children(score,part,"measure").sort((a,b)=>a.number-b.number||idCompare(a,b)),prepared=measures.map(measure=>{const voices=children(score,measure,"voice").sort((a,b)=>a.index-b.index||idCompare(a,b)),leading=profile.measurePadding+profile.clefWidth+profile.keySignatureWidth,voiceEvents=voices.map(voice=>events(score,voice)),naturalWidth=Math.max(request.minimumSystemWidth,leading+profile.barlineWidth+profile.measurePadding,...voiceEvents.map(list=>leading+list.reduce((sum,event)=>sum+eventWidth(event)+profile.eventGap,0)+profile.barlineWidth+profile.measurePadding));return{measure,voices,voiceEvents,naturalWidth};});
            let batch=[];const flush=()=>{if(!batch.length)return;globalSequence+=1;const systemY=y,systemHeight=Math.max(profile.staffHeight,profile.staffHeight+(Math.max(1,...batch.flatMap(value=>value.voices.map(v=>v.index)))-1)*request.staffSpacing),naturalWidth=request.horizontalPadding*2+batch.reduce((sum,value)=>sum+value.naturalWidth,0),overflow=naturalWidth>request.availableWidth;let measureX=request.horizontalPadding;const layoutMeasures=batch.map(value=>{const leading=profile.measurePadding+profile.clefWidth+profile.keySignatureWidth;const placements=[];value.voices.forEach((voice,voiceIndex)=>{let x=measureX+leading;value.voiceEvents[voiceIndex].forEach((event,index)=>{const width=eventWidth(event);placements.push(new LayoutEventPlacement({eventId:event.id,measureId:value.measure.id,voiceId:voice.id,x,y:systemY+58+voiceIndex*request.staffSpacing,width,order:index+1}));x+=width+profile.eventGap;});});const result=new LayoutMeasure({id:value.measure.id,number:value.measure.number,x:measureX,width:value.naturalWidth,naturalWidth:value.naturalWidth,overflow:value.naturalWidth>contentWidth,eventPlacements:placements});measureX+=value.naturalWidth;return result;});const first=batch[0].measure,last=batch.at(-1).measure,id=`${score.score.id}:layout:${profile.id}:part:${part.id}:system:${globalSequence}:${first.id}:${last.id}`;systems.push(new LayoutSystem({id,partId:part.id,sequence:globalSequence,semanticSystemIds:Object.freeze([...new Set(batch.flatMap(value=>semanticIds(request,String(value.measure.id))))]),measures:layoutMeasures,y:systemY,height:systemHeight,naturalWidth,overflow}));y+=systemHeight+request.systemSpacing;batch=[];};
            for(const value of prepared){const hint=request.semanticSystems.find(system=>system.measureIds.includes(String(value.measure.id))),firstInHint=hint?.measureIds[0]===String(value.measure.id);if(batch.length&&firstInHint&&hint.breakPolicy==="mandatory")flush();const proposed=batch.reduce((sum,item)=>sum+item.naturalWidth,0)+value.naturalWidth;if(batch.length&&proposed>contentWidth)flush();batch.push(value);if(value.naturalWidth>contentWidth)flush();}flush();}
        const naturalWidth=Math.max(0,...systems.map(system=>system.naturalWidth)),renderedWidth=Math.max(request.availableWidth,naturalWidth),height=Math.max(1,y-request.systemSpacing+request.horizontalPadding),bounds=new LayoutBounds({x:0,y:0,width:renderedWidth,height});return new LayoutPlan({request,score,systems,bounds,metadata:new LayoutMetadata({profileId:profile.id,availableWidth:request.availableWidth,naturalWidth,overflow:systems.some(system=>system.overflow),systemIds:systems.map(system=>system.id),strategy:{pluginId:String(this.pluginId),strategyId:String(this.id)}})});}
}
