import { cloneDeep, freezeDeep, ValidationError } from "../Foundation/index.js";
import { ScoreGraph } from "../Notation/index.js";
function number(value, field) { value = Number(value); if (!Number.isFinite(value) || value < 0 || value > 1000000) throw new ValidationError(`Layout ${field} is outside safe numeric bounds.`); return value; }
export class LayoutBounds { constructor({ x=0,y=0,width,height }={}) { Object.assign(this,{x:number(x,"bounds.x"),y:number(y,"bounds.y"),width:number(width,"bounds.width"),height:number(height,"bounds.height")}); Object.freeze(this); } }
export class LayoutEventPlacement { constructor({ eventId, measureId, voiceId, x, y, width, order, onset=null }={}) { if (![eventId,measureId,voiceId].every(v=>String(v??"").trim()) || !Number.isSafeInteger(order) || order<1) throw new ValidationError("Invalid layout event placement identity or order."); let normalizedOnset=null; if(onset!==null){if(typeof onset!=="object"||!Number.isSafeInteger(onset.numerator)||onset.numerator<0||!Number.isSafeInteger(onset.denominator)||onset.denominator<1)throw new ValidationError("Layout event placement onset must be null or a non-negative exact rational.");const divisor=((a,b)=>{while(b){const next=a%b;a=b;b=next;}return a;})(onset.numerator,onset.denominator);normalizedOnset=Object.freeze({numerator:onset.numerator/divisor,denominator:onset.denominator/divisor});} Object.assign(this,{eventId:String(eventId),measureId:String(measureId),voiceId:String(voiceId),x:number(x,"event.x"),y:number(y,"event.y"),width:number(width,"event.width"),order,onset:normalizedOnset,timingMode:normalizedOnset===null?"legacy-placement-order":"exact-onset"}); Object.freeze(this); } }
export class LayoutMeasure { constructor({ id, number: sequence, x, width, naturalWidth, overflow=false, eventPlacements=[], timingMode:requestedMode=null }={}) { if (!String(id??"").trim() || !Number.isSafeInteger(sequence) || sequence<1 || !Array.isArray(eventPlacements) || eventPlacements.some(v=>!(v instanceof LayoutEventPlacement))) throw new ValidationError("Invalid layout measure."); if(requestedMode!==null&&!["exact-onset","legacy-placement-order"].includes(requestedMode))throw new ValidationError(`Layout measure "${String(id)}" has an invalid timing mode.`);const modes=new Set(eventPlacements.map(v=>v.timingMode));if(modes.size>1)throw new ValidationError(`Layout measure "${String(id)}" cannot mix exact-onset and legacy placements.`);const placementMode=modes.values().next().value;if(placementMode&&requestedMode&&placementMode!==requestedMode)throw new ValidationError(`Layout measure "${String(id)}" timing mode does not match its placements.`);const timingMode=placementMode??requestedMode??"legacy-placement-order"; Object.assign(this,{id:String(id),number:sequence,x:number(x,"measure.x"),width:number(width,"measure.width"),naturalWidth:number(naturalWidth,"measure.naturalWidth"),overflow:Boolean(overflow),eventPlacements:Object.freeze([...eventPlacements]),timingMode}); Object.freeze(this); } }
export class LayoutSystem { constructor({ id, partId, sequence, semanticSystemIds=[], measures=[], y, height, naturalWidth, overflow=false }={}) { if (![id,partId].every(v=>String(v??"").trim()) || !Number.isSafeInteger(sequence)||sequence<1||!Array.isArray(measures)||!measures.length||measures.some(v=>!(v instanceof LayoutMeasure))) throw new ValidationError("Invalid layout system."); Object.assign(this,{id:String(id),partId:String(partId),sequence,semanticSystemIds:Object.freeze(semanticSystemIds.map(String)),measureIds:Object.freeze(measures.map(v=>v.id)),measures:Object.freeze([...measures]),y:number(y,"system.y"),height:number(height,"system.height"),naturalWidth:number(naturalWidth,"system.naturalWidth"),overflow:Boolean(overflow)}); Object.freeze(this); } }
export class LayoutMetadata { constructor(value={}) { Object.assign(this,freezeDeep(cloneDeep(value))); Object.freeze(this); } }
export class LayoutPlan { constructor({ request, score, systems, bounds, metadata }={}) { if (!request || !(score instanceof ScoreGraph)||score!==request.score||!Array.isArray(systems)||systems.some(v=>!(v instanceof LayoutSystem))||!(bounds instanceof LayoutBounds)||!(metadata instanceof LayoutMetadata)) throw new ValidationError("Invalid LayoutPlan."); const placements=systems.flatMap(s=>s.measures.flatMap(m=>m.eventPlacements)),modes=new Set(systems.flatMap(s=>s.measures.map(m=>m.timingMode)));const timingMode=modes.size>1?"mixed-by-measure":(modes.values().next().value??(metadata.timingMode==="exact-onset"?"exact-onset":"legacy-placement-order")); Object.assign(this,{request,score,systems:Object.freeze([...systems]),placements:Object.freeze(placements),bounds,metadata,timingMode}); Object.freeze(this); } }
