import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it } from "vitest";
import { createWebApplication, TechnicalStudies, TechnicalStudiesPanel } from "../../src/web/index.js";

afterEach(()=>document.body.replaceChildren());
describe("technical studies workspace",()=>{
    it("derives choices from Core and starts with the documented two-octave selected-key draft",async()=>{const runtime=await createWebApplication(),view=render(<TechnicalStudiesPanel engine={runtime.studyEngine} application={runtime.exerciseSetApplication} catalogs={runtime.catalogs} renderingEngine={runtime.rendering} publishingEngine={runtime.publishingEngine}/>);try{expect(typeof TechnicalStudies.TechnicalStudiesPanel).toBe("function");expect(screen.getByLabelText("Study octaves").value).toBe("2");expect(screen.getByLabelText("Study key scope").value).toBe("selected-key");expect(screen.getByLabelText("Study measures per system").value).toBe("4");expect(screen.getByText(/1 keys · 12 sections · 12 exercises/)).toBeTruthy();expect([...screen.getByLabelText("Progression realization").options].map(option=>option.value)).toEqual(runtime.catalogs.studyControls.realizations);}finally{view.unmount();await runtime.dispose();}});
    it("normalizes all-key traversal into deterministic estimates and marks completed output stale",async()=>{const runtime=await createWebApplication(),user=userEvent.setup(),view=render(<TechnicalStudiesPanel engine={runtime.studyEngine} application={runtime.exerciseSetApplication} catalogs={runtime.catalogs} renderingEngine={runtime.rendering}/>);try{await user.selectOptions(screen.getByLabelText("Technical study"),"daily-harmonic-progressions");await user.click(screen.getByRole("button",{name:"Generate technical study"}));expect(await screen.findByRole("heading",{name:"Daily Harmonic Progression Studies"})).toBeTruthy();await user.selectOptions(screen.getByLabelText("Study key scope"),"all-keys");await user.selectOptions(screen.getByLabelText("Study key traversal"),"cycle-of-fifths");expect(screen.getByText(/12 keys · 1 sections · 12 exercises/)).toBeTruthy();expect(screen.getByRole("status").textContent).toMatch(/stale/i);}finally{view.unmount();await runtime.dispose();}});
});
