import React, { StrictMode } from "react"; import { act, render, screen, waitFor } from "@testing-library/react"; import { expect,it,vi } from "vitest"; import { hydrateRoot } from "react-dom/client"; import { renderToString } from "react-dom/server";
import { createWebApplication } from "../../src/web/bootstrap.js"; import { ResponsiveNotation } from "../../src/web/layout/ResponsiveNotation.jsx"; import { presentTrustedSvg } from "../../src/web/layout/presentTrustedSvg.js"; import { buildExerciseApplicationRequest,createInitialExercisePracticeState } from "../../src/web/exercise/workflow.js";

class Observer { static values=[]; constructor(callback){this.callback=callback;this.observe=vi.fn();this.disconnect=vi.fn();Observer.values.push(this);} emit(width){this.callback([{contentRect:{width}}]);} }
async function row(runtime){const request=buildExerciseApplicationRequest(createInitialExercisePracticeState(runtime.catalogs),runtime.catalogs);return runtime.exerciseApplication.run(request).presentation.rows[0];}

it("observes only after mount, coalesces widths, ignores zero, rerenders layout only, and disconnects",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),rendering={render:vi.fn((graph,options)=>runtime.rendering.render(graph,options))},view=render(<ResponsiveNotation row={value} renderingEngine={rendering} ResizeObserver={Observer}/>);expect(Observer.values).toHaveLength(1);expect(Observer.values[0].observe).toHaveBeenCalledTimes(1);await act(async()=>{Observer.values[0].emit(0);Observer.values[0].emit(420);Observer.values[0].emit(420);await Promise.resolve();});await waitFor(()=>expect(rendering.render).toHaveBeenCalledTimes(1));expect(view.container.querySelector(".exercise-svg-frame").dataset.layoutWidth).toBe("420");expect(rendering.render.mock.calls[0][0]).toBe(value.graph);await act(async()=>{Observer.values[0].emit(760);await Promise.resolve();});await waitFor(()=>expect(rendering.render).toHaveBeenCalledTimes(2));view.unmount();expect(Observer.values[0].disconnect).toHaveBeenCalledTimes(1);await runtime.dispose();});

it("ignores stale asynchronous layout success and never updates after unmount",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime);let firstResolve;const first=new Promise(resolve=>{firstResolve=resolve}),wide=runtime.rendering.render(value.graph,{width:800}),rendering={render:vi.fn((graph,options)=>options.width===320?first:Promise.resolve(wide))},view=render(<ResponsiveNotation row={value} renderingEngine={rendering} ResizeObserver={Observer}/>);await act(async()=>{Observer.values[0].emit(320);await Promise.resolve();});await act(async()=>{Observer.values[0].emit(800);await Promise.resolve();});await waitFor(()=>expect(view.container.querySelector(".exercise-svg-frame").dataset.layoutWidth).toBe("800"));await act(async()=>{firstResolve(runtime.rendering.render(value.graph,{width:320}));await first;});expect(view.container.querySelector(".exercise-svg-frame").dataset.layoutWidth).toBe("800");view.unmount();await runtime.dispose();});

it("keeps layout failures separate while preserving authoritative trusted notation",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),view=render(<ResponsiveNotation row={value} renderingEngine={{render(){throw new Error("layout unavailable");}}} ResizeObserver={Observer}/>);await act(async()=>{Observer.values[0].emit(400);await Promise.resolve();});expect((await screen.findByRole("alert")).textContent).toContain("layout unavailable");expect(view.container.querySelector(".exercise-svg-frame svg")).toBeTruthy();view.unmount();await runtime.dispose();});

it("keeps independent observers live through Strict Mode setup and cleanup",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),rendering={render:vi.fn((graph,options)=>runtime.rendering.render(graph,options))},view=render(<StrictMode><ResponsiveNotation row={value} renderingEngine={rendering} ResizeObserver={Observer}/><ResponsiveNotation row={value} renderingEngine={rendering} ResizeObserver={Observer}/></StrictMode>);const active=Observer.values.filter(observer=>observer.disconnect.mock.calls.length===0);expect(active).toHaveLength(2);await act(async()=>{active[0].emit(410);active[1].emit(610);await Promise.resolve();});await waitFor(()=>expect(rendering.render).toHaveBeenCalledTimes(2));expect([...view.container.querySelectorAll(".exercise-svg-frame")].map(node=>node.dataset.layoutWidth)).toEqual(["410","610"]);view.unmount();expect(active.every(observer=>observer.disconnect.mock.calls.length===1)).toBe(true);await runtime.dispose();});

it("assigns deterministic instance-safe accessible title and description ids",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),view=render(<><ResponsiveNotation row={value} renderingEngine={runtime.rendering} ResizeObserver={Observer}/><ResponsiveNotation row={value} renderingEngine={runtime.rendering} ResizeObserver={Observer}/></>);await act(async()=>{Observer.values[0].emit(500);Observer.values[1].emit(500);await Promise.resolve();});await waitFor(()=>expect(view.container.querySelectorAll("svg")).toHaveLength(2));const labels=[...view.container.querySelectorAll("svg")].map(svg=>svg.getAttribute("aria-labelledby"));expect(new Set(labels).size).toBe(2);for(const label of labels)for(const id of label.split(" "))expect(view.container.querySelectorAll(`[id="${id}"]`)).toHaveLength(1);view.unmount();await runtime.dispose();});

it("makes authoritative initial SVG ids instance-safe before observer effects without mutating the row",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),authoritative=value.content,view=render(<><ResponsiveNotation row={value} renderingEngine={runtime.rendering} ResizeObserver={Observer}/><ResponsiveNotation row={value} renderingEngine={runtime.rendering} ResizeObserver={Observer}/></>);const svgs=[...view.container.querySelectorAll("svg")];expect(svgs).toHaveLength(2);for(const attribute of ["aria-labelledby","aria-describedby"]){const references=svgs.map(svg=>svg.getAttribute(attribute));expect(new Set(references).size).toBe(2);references.forEach((id,index)=>{expect(svgs[index].querySelector(`[id="${id}"]`)).toBeTruthy();});}expect(value.content).toBe(authoritative);await act(async()=>{Observer.values[0].emit(0);Observer.values[1].emit(0);await Promise.resolve();});expect([...view.container.querySelectorAll("svg")].map(svg=>svg.getAttribute("aria-labelledby"))).toEqual(svgs.map(svg=>svg.getAttribute("aria-labelledby")));view.unmount();await runtime.dispose();});

it("keeps explicit instance ids stable across SSR, hydration, and responsive replacement",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),element=<ResponsiveNotation row={value} renderingEngine={runtime.rendering} ResizeObserver={Observer} accessibilityIdPrefix="independent-root-a"/>;const markup=renderToString(element),container=document.createElement("div");expect(markup).toContain('id="independent-root-a-score-title"');expect(markup).toContain('aria-labelledby="independent-root-a-score-title"');expect(markup).toContain('aria-describedby="independent-root-a-score-description"');container.innerHTML=markup;document.body.append(container);const before=container.querySelector("svg").outerHTML;let root;await act(async()=>{root=hydrateRoot(container,element);await Promise.resolve();});expect(container.querySelector("svg").outerHTML).toBe(before);await act(async()=>{Observer.values.at(-1).emit(640);await Promise.resolve();});await waitFor(()=>expect(container.querySelector(".exercise-svg-frame").dataset.layoutWidth).toBe("640"));expect(container.querySelector("svg").getAttribute("aria-labelledby")).toBe("independent-root-a-score-title");expect(container.querySelector("#independent-root-a-score-description")).toBeTruthy();await act(async()=>root.unmount());container.remove();await runtime.dispose();});

it("presents only trusted SVG through deterministic targeted accessibility rewriting",async()=>{const runtime=await createWebApplication(),value=await row(runtime),first=presentTrustedSvg(value.content,"explicit-a"),again=presentTrustedSvg(value.content,"explicit-a"),second=presentTrustedSvg(value.content,"explicit-b");expect(first).toBe(again);expect(first).not.toBe(second);expect(first).toContain('aria-labelledby="explicit-a-score-title"');expect(first).toContain('aria-describedby="explicit-a-score-description"');expect(value.content).not.toBe(first);expect(()=>presentTrustedSvg('<svg role="img"><script>alert(1)</script><title id="t">x</title><desc id="d">y</desc></svg>',"unsafe")).toThrow(/trusted SVG/);await runtime.dispose();});
