import React, { StrictMode } from "react"; import { act, render, screen, waitFor } from "@testing-library/react"; import { expect,it,vi } from "vitest";
import { createWebApplication } from "../../src/web/bootstrap.js"; import { ResponsiveNotation } from "../../src/web/layout/ResponsiveNotation.jsx"; import { buildExerciseApplicationRequest,createInitialExercisePracticeState } from "../../src/web/exercise/workflow.js";

class Observer { static values=[]; constructor(callback){this.callback=callback;this.observe=vi.fn();this.disconnect=vi.fn();Observer.values.push(this);} emit(width){this.callback([{contentRect:{width}}]);} }
async function row(runtime){const request=buildExerciseApplicationRequest(createInitialExercisePracticeState(runtime.catalogs),runtime.catalogs);return runtime.exerciseApplication.run(request).presentation.rows[0];}

it("observes only after mount, coalesces widths, ignores zero, rerenders layout only, and disconnects",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),rendering={render:vi.fn((graph,options)=>runtime.rendering.render(graph,options))},view=render(<ResponsiveNotation row={value} renderingEngine={rendering} ResizeObserver={Observer}/>);expect(Observer.values).toHaveLength(1);expect(Observer.values[0].observe).toHaveBeenCalledTimes(1);await act(async()=>{Observer.values[0].emit(0);Observer.values[0].emit(420);Observer.values[0].emit(420);await Promise.resolve();});await waitFor(()=>expect(rendering.render).toHaveBeenCalledTimes(1));expect(view.container.querySelector(".exercise-svg-frame").dataset.layoutWidth).toBe("420");expect(rendering.render.mock.calls[0][0]).toBe(value.graph);await act(async()=>{Observer.values[0].emit(760);await Promise.resolve();});await waitFor(()=>expect(rendering.render).toHaveBeenCalledTimes(2));view.unmount();expect(Observer.values[0].disconnect).toHaveBeenCalledTimes(1);await runtime.dispose();});

it("ignores stale asynchronous layout success and never updates after unmount",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime);let firstResolve;const first=new Promise(resolve=>{firstResolve=resolve}),wide=runtime.rendering.render(value.graph,{width:800}),rendering={render:vi.fn((graph,options)=>options.width===320?first:Promise.resolve(wide))},view=render(<ResponsiveNotation row={value} renderingEngine={rendering} ResizeObserver={Observer}/>);await act(async()=>{Observer.values[0].emit(320);await Promise.resolve();});await act(async()=>{Observer.values[0].emit(800);await Promise.resolve();});await waitFor(()=>expect(view.container.querySelector(".exercise-svg-frame").dataset.layoutWidth).toBe("800"));await act(async()=>{firstResolve(runtime.rendering.render(value.graph,{width:320}));await first;});expect(view.container.querySelector(".exercise-svg-frame").dataset.layoutWidth).toBe("800");view.unmount();await runtime.dispose();});

it("keeps layout failures separate while preserving authoritative trusted notation",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),view=render(<ResponsiveNotation row={value} renderingEngine={{render(){throw new Error("layout unavailable");}}} ResizeObserver={Observer}/>);await act(async()=>{Observer.values[0].emit(400);await Promise.resolve();});expect((await screen.findByRole("alert")).textContent).toContain("layout unavailable");expect(view.container.querySelector(".exercise-svg-frame svg")).toBeTruthy();view.unmount();await runtime.dispose();});

it("keeps independent observers live through Strict Mode setup and cleanup",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),rendering={render:vi.fn((graph,options)=>runtime.rendering.render(graph,options))},view=render(<StrictMode><ResponsiveNotation row={value} renderingEngine={rendering} ResizeObserver={Observer}/><ResponsiveNotation row={value} renderingEngine={rendering} ResizeObserver={Observer}/></StrictMode>);const active=Observer.values.filter(observer=>observer.disconnect.mock.calls.length===0);expect(active).toHaveLength(2);await act(async()=>{active[0].emit(410);active[1].emit(610);await Promise.resolve();});await waitFor(()=>expect(rendering.render).toHaveBeenCalledTimes(2));expect([...view.container.querySelectorAll(".exercise-svg-frame")].map(node=>node.dataset.layoutWidth)).toEqual(["410","610"]);view.unmount();expect(active.every(observer=>observer.disconnect.mock.calls.length===1)).toBe(true);await runtime.dispose();});

it("assigns deterministic instance-safe accessible title and description ids",async()=>{Observer.values=[];const runtime=await createWebApplication(),value=await row(runtime),view=render(<><ResponsiveNotation row={value} renderingEngine={runtime.rendering} ResizeObserver={Observer}/><ResponsiveNotation row={value} renderingEngine={runtime.rendering} ResizeObserver={Observer}/></>);await act(async()=>{Observer.values[0].emit(500);Observer.values[1].emit(500);await Promise.resolve();});await waitFor(()=>expect(view.container.querySelectorAll("svg")).toHaveLength(2));const labels=[...view.container.querySelectorAll("svg")].map(svg=>svg.getAttribute("aria-labelledby"));expect(new Set(labels).size).toBe(2);for(const label of labels)for(const id of label.split(" "))expect(view.container.querySelectorAll(`[id="${id}"]`)).toHaveLength(1);view.unmount();await runtime.dispose();});
