import { useEffect, useId, useMemo, useRef, useState } from "react";
import { ExerciseSetWorksheet } from "../exercise-set/ExerciseSetPanel.jsx";
import { validateExerciseSetPresentation } from "../exercise-set/presentation.js";

const message=error=>error?.cause?.message??error?.message??"Curriculum generation failed.";
function ParameterControl({parameter,value,onChange}){
    if(parameter.fixed)return <div className="curriculum-fixed"><dt>{parameter.label}</dt><dd>{typeof parameter.defaultValue==="object"?JSON.stringify(parameter.defaultValue):String(parameter.defaultValue)} <span>(fixed)</span></dd></div>;
    if(parameter.contract==="boolean")return <label className="check-field"><input type="checkbox" checked={Boolean(value)} onChange={event=>onChange(event.target.checked)}/>{parameter.label}</label>;
    if(parameter.choices)return <label className="field"><span>{parameter.label}</span><select value={typeof value==="object"?JSON.stringify(value):String(value??"")} onChange={event=>{const choice=parameter.choices.find(option=>String(option.id)===event.target.value);onChange(choice?.value??choice?.id??event.target.value);}}>{parameter.choices.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select>{parameter.helpText&&<small>{parameter.helpText}</small>}</label>;
    return <label className="field"><span>{parameter.label}</span><input value={String(value??"")} onChange={event=>onChange(parameter.contract==="integer"?Number(event.target.value):event.target.value)}/>{parameter.helpText&&<small>{parameter.helpText}</small>}</label>;
}
function Structure({curriculum}){return <div className="curriculum-structure">{curriculum.units.map(unit=><section key={unit.id}><h4>{unit.title}</h4><p>{unit.objective}</p><ol>{unit.lessons.map(lesson=><li key={lesson.id}><strong>{lesson.title}</strong> — {lesson.objective}{lesson.prerequisites.length>0&&<small> Prerequisites: {lesson.prerequisites.join(", ")}</small>}</li>)}</ol></section>)}</div>;}
export function CurriculumBrowser({engine,application,catalogs,renderingEngine,ResizeObserver,accessibilityIdPrefix}){
    const id=useId(),[mode,setMode]=useState("templates"),[family,setFamily]=useState("all"),[difficulty,setDifficulty]=useState("all"),[tag,setTag]=useState("all"),[selectedTemplate,setSelectedTemplate]=useState(catalogs.templates[0]?.key??""),[selectedCurriculum,setSelectedCurriculum]=useState(catalogs.curricula[0]?.key??""),[unitId,setUnitId]=useState(""),[lessonId,setLessonId]=useState(""),[overrides,setOverrides]=useState({}),[revision,setRevision]=useState(0),[workflow,setWorkflow]=useState({busy:false,result:null,resultRevision:null,error:null}),operation=useRef(0),resultRef=useRef(null);
    const tags=useMemo(()=>[...new Set([...catalogs.templates,...catalogs.curricula].flatMap(value=>value.tags))].sort(),[catalogs]);
    const templates=catalogs.templates.filter(value=>(family==="all"||value.family===family)&&(difficulty==="all"||value.difficulty===difficulty)&&(tag==="all"||value.tags.includes(tag)));
    const curricula=catalogs.curricula.filter(value=>(difficulty==="all"||value.difficulty===difficulty)&&(tag==="all"||value.tags.includes(tag)));
    const template=templates.find(value=>value.key===selectedTemplate)??templates[0]??null,curriculum=curricula.find(value=>value.key===selectedCurriculum)??curricula[0]??null;
    const unit=curriculum?.units.find(value=>value.id===unitId)??null;
    useEffect(()=>{if(template){setOverrides(Object.fromEntries(template.parameters.filter(value=>!value.fixed&&value.defaultValue!==null).map(value=>[value.id,value.defaultValue])));setRevision(value=>value+1);}},[template?.key]);
    const change=(parameter,value)=>{setOverrides(current=>({...current,[parameter]:value}));setRevision(value=>value+1);};
    const changeMode=next=>{if(next===mode)return;operation.current+=1;setMode(next);setRevision(value=>value+1);setWorkflow(value=>({...value,busy:false,error:null}));};
    const generate=()=>{const current=++operation.current;setWorkflow(value=>({...value,busy:true,error:null}));let expansion;try{expansion=mode==="templates"?engine.expandTemplate({templateId:template.id,pluginId:template.pluginId,overrides}):engine.expandCurriculum({curriculumId:curriculum.id,pluginId:curriculum.pluginId,unitId:unitId||null,lessonId:lessonId||null});}catch(error){setWorkflow(value=>({...value,busy:false,error}));return;}Promise.resolve().then(()=>application.run(expansion.exerciseSetRequest)).then(result=>{validateExerciseSetPresentation(result);if(operation.current===current)setWorkflow({busy:false,result,resultRevision:revision,error:null});}).catch(error=>{if(operation.current===current)setWorkflow(value=>({...value,busy:false,error}));});};
    useEffect(()=>{if(workflow.result)resultRef.current?.focus();},[workflow.result]);
    let browserContent;
    if(mode==="templates"){
        browserContent=templates.length?<><label className="field"><span>Template</span><select value={template?.key??""} onChange={event=>setSelectedTemplate(event.target.value)}>{templates.map(value=><option key={value.key} value={value.key}>{value.name}</option>)}</select></label><article><h3>{template.name}</h3><p>{template.description}</p><p><strong>Objective:</strong> {template.objective}</p><p><strong>Difficulty:</strong> {template.difficulty}</p>{template.prerequisites.length>0&&<p><strong>Prerequisites:</strong> {template.prerequisites.join(", ")}</p>}<fieldset><legend>Template parameters</legend><dl>{template.parameters.filter(value=>value.fixed).map(parameter=><ParameterControl key={parameter.id} parameter={parameter} value={parameter.defaultValue}/>)}</dl>{template.parameters.filter(value=>!value.fixed).map(parameter=><ParameterControl key={parameter.id} parameter={parameter} value={overrides[parameter.id]} onChange={value=>change(parameter.id,value)}/>)}</fieldset></article></>:<p className="exercise-empty">No templates match these filters.</p>;
    }else{
        browserContent=curricula.length?<><label className="field"><span>Curriculum</span><select value={curriculum?.key??""} onChange={event=>{setSelectedCurriculum(event.target.value);setUnitId("");setLessonId("");setRevision(value=>value+1);}}>{curricula.map(value=><option key={value.key} value={value.key}>{value.title}</option>)}</select></label><article><h3>{curriculum.title}</h3><p>{curriculum.description}</p><p><strong>Objective:</strong> {curriculum.objective}</p><p><strong>Difficulty:</strong> {curriculum.difficulty}</p>{curriculum.prerequisites.length>0&&<p><strong>Prerequisites:</strong> {curriculum.prerequisites.join(", ")}</p>}<Structure curriculum={curriculum}/><label className="field"><span>Unit scope</span><select value={unitId} onChange={event=>{setUnitId(event.target.value);setLessonId("");setRevision(value=>value+1);}}><option value="">Complete curriculum</option>{curriculum.units.map(value=><option key={value.id} value={value.id}>{value.title}</option>)}</select><small>Select a unit before selecting one of its lessons.</small></label>{unit&&<label className="field"><span>Lesson scope for {unit.title}</span><select value={lessonId?JSON.stringify([unit.id,lessonId]):""} onChange={event=>{const selected=unit.lessons.find(lesson=>JSON.stringify([unit.id,lesson.id])===event.target.value);setLessonId(selected?.id??"");setRevision(value=>value+1);}}><option value="">Complete unit</option>{unit.lessons.map(lesson=><option key={`${unit.id}:${lesson.id}`} value={JSON.stringify([unit.id,lesson.id])}>{lesson.title} ({unit.title})</option>)}</select></label>}</article></>:<p className="exercise-empty">No curricula match these filters.</p>;
    }
    return <section className="curriculum-browser" aria-labelledby={`${id}-title`}><header><p className="eyebrow">v8.9 · Curriculum workflow</p><h2 id={`${id}-title`}>Exercise Templates and Curricula</h2><p>Expand reusable pedagogical intent through the authoritative worksheet pipeline.</p></header>
        <div className="curriculum-tabs" role="tablist" aria-label="Curriculum browser mode"><button role="tab" aria-selected={mode==="templates"} onClick={()=>changeMode("templates")}>Templates</button><button role="tab" aria-selected={mode==="curricula"} onClick={()=>changeMode("curricula")}>Curricula</button></div>
        <div className="curriculum-filters"><label className="field"><span>Difficulty</span><select value={difficulty} onChange={event=>setDifficulty(event.target.value)}><option value="all">All difficulties</option>{["beginner","intermediate","advanced"].map(value=><option key={value}>{value}</option>)}</select></label><label className="field"><span>Skill or tag</span><select value={tag} onChange={event=>setTag(event.target.value)}><option value="all">All skills</option>{tags.map(value=><option key={value}>{value}</option>)}</select></label>{mode==="templates"&&<label className="field"><span>Family</span><select value={family} onChange={event=>setFamily(event.target.value)}><option value="all">All families</option>{[...new Set(catalogs.templates.map(value=>value.family))].sort().map(value=><option key={value}>{value}</option>)}</select></label>}</div>
        <div className="curriculum-workspace"><div>{browserContent}</div>
            <section aria-label="Curriculum worksheet result" aria-busy={workflow.busy}><button className="primary-action" type="button" disabled={workflow.busy||(!template&&mode==="templates")||(!curriculum&&mode==="curricula")} onClick={generate}>{workflow.busy?"Expanding…":mode==="templates"?"Expand Template":"Expand Curriculum"}</button><p className="exercise-live" aria-live="polite">{workflow.busy?"Expansion and worksheet generation in progress…":workflow.resultRevision!==revision&&workflow.result?"The retained curriculum worksheet is stale.":workflow.result?"Curriculum worksheet ready.":"Select and expand a study."}</p>{workflow.error&&<div className="exercise-error" role="alert"><strong>Expansion failed.</strong> {message(workflow.error)}</div>}<ExerciseSetWorksheet id={`${id}-curriculum`} result={workflow.result} stale={Boolean(workflow.result)&&workflow.resultRevision!==revision} resultRef={resultRef} renderingEngine={renderingEngine} ResizeObserver={ResizeObserver} accessibilityIdPrefix={accessibilityIdPrefix}/></section>
        </div></section>;
}
export default CurriculumBrowser;
