import { ValidationError } from "../Foundation/index.js";
import { CurriculumEngine } from "./CurriculumEngine.js";
import { CurriculumCatalog, ExerciseTemplateCatalog } from "./catalogs.js";
import { builtInCurricula, builtInExerciseTemplates } from "./builtins.js";
import { curriculumExpansionDescriptor, curriculumPluginDescriptor, curriculumServiceDescriptors } from "./descriptors.js";
import { curriculumPackageDescriptor } from "./package.descriptor.js";
const undoAll=actions=>{const errors=[];for(const action of [...actions].reverse())try{action();}catch(error){errors.push(error);}return errors;};
export class CurriculumModule{
    #configured=false;#undo=[];#injectedTemplates;#injectedCurricula;#injectedEngine;
    constructor({templateCatalog=null,curriculumCatalog=null,engine=null}={}){this.id=String(curriculumPackageDescriptor.id);this.descriptor=curriculumPackageDescriptor;this.#injectedTemplates=templateCatalog;this.#injectedCurricula=curriculumCatalog;this.#injectedEngine=engine;this.templateCatalog=templateCatalog;this.curriculumCatalog=curriculumCatalog;this.engine=engine;this.plugin=null;Object.seal(this);}
    configure({services,registries}){if(this.#configured)return this;let scaleCatalog,chordCatalog,progressionCatalog;try{scaleCatalog=services.resolve("theory.scaleCatalog");chordCatalog=services.resolve("theory.chordCatalog");progressionCatalog=services.resolve("exercise.progressionCatalog");}catch(cause){throw new ValidationError("CurriculumModule requires active Theory and progression catalogs.",{cause});}
        const templateCatalog=this.#injectedTemplates??new ExerciseTemplateCatalog(),curriculumCatalog=this.#injectedCurricula??new CurriculumCatalog(templateCatalog),engine=this.#injectedEngine??new CurriculumEngine({templateCatalog,curriculumCatalog,scaleCatalog,chordCatalog,progressionCatalog}),plugin=Object.freeze({id:String(curriculumPluginDescriptor.id),templates:builtInExerciseTemplates,curricula:builtInCurricula}),undo=[];
        const service=(id,value)=>{services.register(id,value);undo.push(()=>{if(services.resolve(id,{optional:true})===value)services.unregister(id);});};
        const record=(registry,descriptor,value)=>{const previous=registry.getRecord(descriptor.id);let inserted=null;const remove=current=>{if(registry.getRecord(descriptor.id)===current)registry.unregister(descriptor.id);};try{inserted=registry.register(descriptor,{value});}catch(error){const current=registry.getRecord(descriptor.id);if(!previous&&current?.descriptor===descriptor&&current?.value===value)try{remove(current);}catch{}throw error;}undo.push(()=>remove(inserted));};
        try{for(const template of builtInExerciseTemplates){const existing=templateCatalog.get(curriculumPluginDescriptor.id,template.id);if(existing&&existing!==template)throw new ValidationError(`Built-in template collision: "${template.id}".`);if(!existing){templateCatalog.register(curriculumPluginDescriptor.id,template);undo.push(()=>{if(templateCatalog.get(curriculumPluginDescriptor.id,template.id)===template)templateCatalog.remove(curriculumPluginDescriptor.id,template.id);});}}
            for(const curriculum of builtInCurricula){const existing=curriculumCatalog.get(curriculumPluginDescriptor.id,curriculum.id);if(existing&&existing!==curriculum)throw new ValidationError(`Built-in curriculum collision: "${curriculum.id}".`);if(!existing){curriculumCatalog.register(curriculumPluginDescriptor.id,curriculum);undo.push(()=>{if(curriculumCatalog.get(curriculumPluginDescriptor.id,curriculum.id)===curriculum)curriculumCatalog.remove(curriculumPluginDescriptor.id,curriculum.id);});}}
            service("curriculum.template-catalog",templateCatalog);service("curriculum.catalog",curriculumCatalog);service("curriculum.engine",engine);record(registries.services,curriculumServiceDescriptors.templates,templateCatalog);record(registries.services,curriculumServiceDescriptors.curricula,curriculumCatalog);record(registries.services,curriculumServiceDescriptors.engine,engine);record(registries.plugins,curriculumPluginDescriptor,plugin);record(registries.exercises,curriculumExpansionDescriptor,engine);this.templateCatalog=templateCatalog;this.curriculumCatalog=curriculumCatalog;this.engine=engine;this.plugin=plugin;this.#undo=undo;this.#configured=true;return this;
        }catch(error){const failures=undoAll(undo);if(failures.length)throw new AggregateError([error,...failures],"CurriculumModule configuration and rollback failed.",{cause:error});throw error;}}
    dispose(){const errors=undoAll(this.#undo);this.#undo=[];this.#configured=false;if(!this.#injectedTemplates)this.templateCatalog=null;if(!this.#injectedCurricula)this.curriculumCatalog=null;if(!this.#injectedEngine)this.engine=null;this.plugin=null;if(errors.length)throw new AggregateError(errors,"CurriculumModule disposal failed.");return this;}
}
export default CurriculumModule;
