import { cloneDeep, freezeDeep, ValidationError } from "../Foundation/index.js";
import { ExerciseRequest, ExerciseType } from "../Exercise/index.js";
import { ExerciseApplicationRequest } from "../ExerciseApplication/index.js";
import { ExerciseSetRequest } from "../ExerciseSet/index.js";
import { CurriculumExpansionRequest, CurriculumExpansionResult, ExerciseTemplateExpansion, ExerciseTemplateRequest } from "./values.js";

const exerciseFields=new Set(["root","roots","allKeys","pattern","quality","direction","octaves","startingOctave","approachPattern","enclosurePattern","target","progression"]);
const notationFields=new Set(["duration","clef","timeSignature","measuresPerSystem","keySignaturePolicy"]);
function validateContract(parameter,value,templateId){
    const fail=message=>{throw new ValidationError(`Template "${templateId}" parameter "${parameter.id}" ${message}.`);};
    if(parameter.contract==="boolean"&&typeof value!=="boolean")fail("must be boolean");
    if(parameter.contract==="integer"&&!Number.isSafeInteger(value))fail("must be a safe integer");
    if(["string","root","choice"].includes(parameter.contract)&&typeof value!=="string")fail("must be a string");
    if(parameter.contract==="duration"&&(!value||typeof value!=="object"||!Number.isSafeInteger(value.numerator)||!Number.isSafeInteger(value.denominator)))fail("must be an exact rational object");
    if(parameter.contract==="roots"&&(!Array.isArray(value)||!value.length))fail("must be a non-empty ordered array");
    if(parameter.contract==="object"&&(!value||typeof value!=="object"||Array.isArray(value)))fail("must be an object");
    if(parameter.allowedValues&&!parameter.allowedValues.some(entry=>JSON.stringify(entry)===JSON.stringify(value)&&typeof entry===typeof value))fail("is not an allowed value");
}
export class CurriculumEngine{
    constructor({templateCatalog,curriculumCatalog,scaleCatalog,chordCatalog,progressionCatalog}={}){if(!templateCatalog?.get||!curriculumCatalog?.get||!scaleCatalog?.get||!chordCatalog?.get||!progressionCatalog?.get)throw new ValidationError("CurriculumEngine requires active template, curriculum, Theory, and progression catalogs.");Object.defineProperties(this,{templateCatalog:{value:templateCatalog},curriculumCatalog:{value:curriculumCatalog},scaleCatalog:{value:scaleCatalog},chordCatalog:{value:chordCatalog},progressionCatalog:{value:progressionCatalog}});Object.freeze(this);}
    expandTemplate(input){const request=input instanceof ExerciseTemplateRequest?input:new ExerciseTemplateRequest(input),template=this.templateCatalog.get(request.pluginId,request.templateId,{required:true}),definitions=new Map(template.parameters.map(value=>[value.id,value]));for(const key of Object.keys(request.overrides)){const parameter=definitions.get(key);if(!parameter)throw new ValidationError(`Template "${template.id}" received unknown parameter "${key}".`);if(Object.hasOwn(template.constraints,key)||!parameter.overridable)throw new ValidationError(`Template "${template.id}" parameter "${key}" is fixed and cannot be overridden.`);}
        const values={};for(const parameter of template.parameters){const selected=Object.hasOwn(template.constraints,parameter.id)?template.constraints[parameter.id]:Object.hasOwn(request.overrides,parameter.id)?request.overrides[parameter.id]:Object.hasOwn(template.defaults,parameter.id)?template.defaults[parameter.id]:parameter.defaultValue;if(selected===undefined){if(parameter.required)throw new ValidationError(`Template "${template.id}" requires parameter "${parameter.id}".`);continue;}validateContract(parameter,selected,template.id);if(parameter.validationSource==="theory.scaleCatalog")this.scaleCatalog.get(selected,{required:true});if(parameter.validationSource==="theory.chordCatalog")this.chordCatalog.get(selected,{required:true});if(parameter.validationSource==="exercise.progressionCatalog")this.progressionCatalog.get(selected,{required:true});values[parameter.id]=cloneDeep(selected);}
        const exercise={type:String(ExerciseType.from(template.family))};for(const [key,value]of Object.entries(values))if(exerciseFields.has(key))exercise[key]=value;
        if(exercise.allKeys){delete exercise.root;delete exercise.roots;}
        const notation={};for(const [key,value]of Object.entries(values))if(notationFields.has(key))notation[key]=value;
        const rendering={format:"svg",options:{layoutProfile:values.layoutProfile??"print-worksheet"}};
        try{new ExerciseRequest(exercise);}catch(cause){throw new ValidationError(`Template "${template.id}" expansion is invalid: ${cause.message}`,{cause});}
        const application=new ExerciseApplicationRequest({exercise,notation,rendering}),trace=freezeDeep({templateId:template.id,templateVersion:template.version,family:String(template.family),parameters:cloneDeep(values)});
        const set=new ExerciseSetRequest({id:`template-${template.id}`,title:template.name,instructions:template.instructions??undefined,sections:[{id:`template-${template.id}-section`,title:template.sectionLabel??template.name,metadata:trace,items:[{id:`template-${template.id}-item`,label:values.itemLabel??template.itemLabel??template.name,metadata:trace,application}]}]});
        return new ExerciseTemplateExpansion({template,request,parameters:values,exerciseSetRequest:set});}
    expandCurriculum(input){const request=input instanceof CurriculumExpansionRequest?input:new CurriculumExpansionRequest(input),curriculum=this.curriculumCatalog.get(request.pluginId,request.curriculumId,{required:true});let units=curriculum.units;if(request.unitId){const selected=curriculum.units.find(value=>value.id===request.unitId);if(!selected)throw new ValidationError(`Curriculum "${curriculum.id}" does not contain unit "${request.unitId}".`);units=[selected];}const sections=[];for(const unit of units){let lessons=unit.lessons;if(request.lessonId){const selected=unit.lessons.find(value=>value.id===request.lessonId);if(!selected)throw new ValidationError(`Curriculum "${curriculum.id}" unit "${unit.id}" does not contain lesson "${request.lessonId}".`);lessons=[selected];}for(const lesson of lessons){const items=lesson.templates.map((reference,index)=>{const overrides={...(request.overrides[reference.templateId]??{}),...reference.overrides};const expansion=this.expandTemplate({templateId:reference.templateId,pluginId:reference.pluginId,overrides});const trace={curriculumId:curriculum.id,curriculumVersion:curriculum.version,unitId:unit.id,lessonId:lesson.id,templateId:expansion.template.id,templateVersion:expansion.template.version,family:String(expansion.template.family),parameters:expansion.parameters};return{id:`${curriculum.id}-${unit.id}-${lesson.id}-${index+1}`,label:reference.label??expansion.template.itemLabel??expansion.template.name,metadata:trace,application:expansion.exerciseSetRequest.items[0].application};});sections.push({id:`${curriculum.id}-${unit.id}-${lesson.id}`,title:lesson.title,label:unit.title,metadata:{curriculumId:curriculum.id,unitId:unit.id,lessonId:lesson.id,difficulty:String(lesson.difficulty)},items});}}
        const scope=request.lessonId?`-${request.unitId}-${request.lessonId}`:request.unitId?`-${request.unitId}`:"",exerciseSetRequest=new ExerciseSetRequest({id:`curriculum-${curriculum.id}${scope}`,title:request.lessonId?sections[0].title:request.unitId?units[0].title:curriculum.title,subtitle:curriculum.description,instructions:curriculum.objective,sections});return new CurriculumExpansionResult({request,curriculum,exerciseSetRequest,metadata:{curriculumId:curriculum.id,unitId:request.unitId,lessonId:request.lessonId,sectionCount:sections.length,itemCount:exerciseSetRequest.items.length,deterministic:true}});}
}
