import { cloneDeep, freezeDeep, ValidationError } from "../Foundation/index.js";
import { ExerciseRequest, ExerciseType } from "../Exercise/index.js";
import { ExerciseApplicationRequest } from "../ExerciseApplication/index.js";
import { boundedExerciseSetId, EXERCISE_SET_LIMITS, ExerciseSetRequest } from "../ExerciseSet/index.js";
import { CurriculumExpansionRequest, CurriculumExpansionResult, ExerciseTemplateExpansion, ExerciseTemplateRequest } from "./values.js";

const exerciseFields=new Set(["root","roots","allKeys","pattern","quality","direction","octaves","startingOctave","approachPattern","enclosurePattern","target","progression"]);
const notationFields=new Set(["duration","clef","timeSignature","measuresPerSystem","keySignaturePolicy"]);
function validateContract(parameter,value,templateId){
    const fail=message=>{throw new ValidationError(`Template "${templateId}" parameter "${parameter.id}" ${message}.`);};
    if(parameter.contract==="boolean"&&typeof value!=="boolean")fail("must be boolean");
    if(parameter.contract==="integer"&&!Number.isSafeInteger(value))fail("must be a safe integer");
    if(["string","root","choice"].includes(parameter.contract)&&typeof value!=="string")fail("must be a string");
    if(parameter.contract==="duration"&&(!value||typeof value!=="object"||!Number.isSafeInteger(value.numerator)||!Number.isSafeInteger(value.denominator)))fail("must be an exact rational object");
    if(parameter.contract==="roots"&&(!Array.isArray(value)||!value.length))fail("must be a non-empty ordered array");
    if(parameter.contract==="object"&&(!value||typeof value!=="object"||Array.isArray(value)))fail("must be an object");
    if(parameter.allowedValues&&!parameter.allowedValues.some(entry=>JSON.stringify(entry)===JSON.stringify(value)&&typeof entry===typeof value))fail("is not an allowed value");
}
function unique(target,id,context){if(target.has(id))throw new ValidationError(`Generated ExerciseSet ID collision "${id}" while planning ${context}.`);target.add(id);return id;}
function generated(kind,readable,identity){return boundedExerciseSetId({kind,readable,identity});}

export class CurriculumEngine{
    constructor({templateCatalog,curriculumCatalog,scaleCatalog,chordCatalog,progressionCatalog}={}){if(!templateCatalog?.get||!curriculumCatalog?.get||!scaleCatalog?.get||!chordCatalog?.get||!progressionCatalog?.get)throw new ValidationError("CurriculumEngine requires active template, curriculum, Theory, and progression catalogs.");Object.defineProperties(this,{templateCatalog:{value:templateCatalog},curriculumCatalog:{value:curriculumCatalog},scaleCatalog:{value:scaleCatalog},chordCatalog:{value:chordCatalog},progressionCatalog:{value:progressionCatalog}});Object.freeze(this);}
    #planTemplate(input){
        const request=input instanceof ExerciseTemplateRequest?input:new ExerciseTemplateRequest(input),template=this.templateCatalog.get(request.pluginId,request.templateId,{required:true}),definitions=new Map(template.parameters.map(value=>[value.id,value]));
        for(const key of Object.keys(request.overrides)){const parameter=definitions.get(key);if(!parameter)throw new ValidationError(`Template "${request.pluginId}:${template.id}" received unknown parameter "${key}".`);if(Object.hasOwn(template.constraints,key)||!parameter.overridable)throw new ValidationError(`Template "${request.pluginId}:${template.id}" parameter "${key}" is fixed and cannot be overridden.`);}
        const values={};for(const parameter of template.parameters){const selected=Object.hasOwn(template.constraints,parameter.id)?template.constraints[parameter.id]:Object.hasOwn(request.overrides,parameter.id)?request.overrides[parameter.id]:Object.hasOwn(template.defaults,parameter.id)?template.defaults[parameter.id]:parameter.defaultValue;if(selected===undefined){if(parameter.required)throw new ValidationError(`Template "${request.pluginId}:${template.id}" requires parameter "${parameter.id}".`);continue;}validateContract(parameter,selected,template.id);if(parameter.validationSource==="theory.scaleCatalog")this.scaleCatalog.get(selected,{required:true});if(parameter.validationSource==="theory.chordCatalog")this.chordCatalog.get(selected,{required:true});if(parameter.validationSource==="exercise.progressionCatalog")this.progressionCatalog.get(selected,{required:true});values[parameter.id]=cloneDeep(selected);}
        const exercise={type:String(ExerciseType.from(template.family))};for(const [key,value]of Object.entries(values))if(exerciseFields.has(key))exercise[key]=value;if(exercise.allKeys){delete exercise.root;delete exercise.roots;}
        const notation={};for(const [key,value]of Object.entries(values))if(notationFields.has(key))notation[key]=value;
        try{new ExerciseRequest(exercise);}catch(cause){throw new ValidationError(`Template "${request.pluginId}:${template.id}" expansion is invalid: ${cause.message}`,{cause});}
        return freezeDeep({request,template,templatePluginId:request.pluginId,values,application:new ExerciseApplicationRequest({exercise,notation,rendering:{format:"svg",options:{layoutProfile:values.layoutProfile??"print-worksheet"}}})});
    }
    expandTemplate(input){
        const plan=this.#planTemplate(input),base={mode:"template",templatePluginId:plan.templatePluginId,templateId:plan.template.id,templateVersion:plan.template.version,family:String(plan.template.family),parameters:plan.values};
        const setId=generated("template-set",`${plan.templatePluginId}-${plan.template.id}`,base),sectionId=generated("template-section",plan.template.id,{...base,position:1}),itemId=generated("template-item",plan.template.id,{...base,sectionPosition:1,itemPosition:1}),traceId=generated("template-trace",plan.template.id,{...base,setId,sectionId,itemId});
        const trace=freezeDeep({traceId,templatePluginId:plan.templatePluginId,templateId:plan.template.id,templateVersion:plan.template.version,family:String(plan.template.family),parameters:cloneDeep(plan.values),generatedExerciseSetId:setId,generatedSectionId:sectionId,generatedItemId:itemId});
        const set=new ExerciseSetRequest({id:setId,title:plan.template.name,instructions:plan.template.instructions??undefined,sections:[{id:sectionId,title:plan.template.sectionLabel??plan.template.name,metadata:trace,items:[{id:itemId,label:plan.values.itemLabel??plan.template.itemLabel??plan.template.name,metadata:trace,application:plan.application}]}]});
        return new ExerciseTemplateExpansion({template:plan.template,request:plan.request,parameters:plan.values,exerciseSetRequest:set});
    }
    expandCurriculum(input){
        const request=input instanceof CurriculumExpansionRequest?input:new CurriculumExpansionRequest(input),curriculum=this.curriculumCatalog.get(request.pluginId,request.curriculumId,{required:true});
        let units=curriculum.units;if(request.unitId){const selected=curriculum.units.find(value=>value.id===request.unitId);if(!selected)throw new ValidationError(`Curriculum "${request.pluginId}:${curriculum.id}" does not contain unit "${request.unitId}".`);units=[selected];}
        const selectedLessons=[];for(const unit of units){let lessons=unit.lessons;if(request.lessonId){const selected=unit.lessons.find(value=>value.id===request.lessonId);if(!selected)throw new ValidationError(`Curriculum "${request.pluginId}:${curriculum.id}" unit "${unit.id}" does not contain lesson "${request.lessonId}".`);lessons=[selected];}for(const lesson of lessons)selectedLessons.push({unit,lesson});}
        if(selectedLessons.length>EXERCISE_SET_LIMITS.sections)throw new ValidationError(`Curriculum "${request.pluginId}:${curriculum.id}" expansion has ${selectedLessons.length} lessons; ExerciseSet supports at most ${EXERCISE_SET_LIMITS.sections} sections.`);
        const base={mode:"curriculum",curriculumPluginId:request.pluginId,curriculumId:curriculum.id,curriculumVersion:curriculum.version,unitId:request.unitId,lessonId:request.lessonId},setId=generated("curriculum-set",`${request.pluginId}-${curriculum.id}`,base),sectionIds=new Set(),itemIds=new Set(),planned=[];let totalItems=0;
        for(const [sectionIndex,{unit,lesson}] of selectedLessons.entries()){
            if(lesson.templates.length>EXERCISE_SET_LIMITS.itemsPerSection)throw new ValidationError(`Curriculum "${request.pluginId}:${curriculum.id}" unit "${unit.id}" lesson "${lesson.id}" expands to ${lesson.templates.length} items; ExerciseSet supports at most ${EXERCISE_SET_LIMITS.itemsPerSection} items per section.`);
            const sectionIdentity={...base,unitId:unit.id,lessonId:lesson.id,sectionPosition:sectionIndex+1},sectionId=unique(sectionIds,generated("curriculum-section",`${unit.id}-${lesson.id}`,sectionIdentity),`curriculum "${curriculum.id}" unit "${unit.id}" lesson "${lesson.id}"`);
            const items=lesson.templates.map((reference,itemIndex)=>{const templatePluginId=reference.pluginId??request.pluginId,qualified=`${templatePluginId}:${reference.templateId}`,overrides={...(request.overrides[qualified]??request.overrides[reference.templateId]??{}),...reference.overrides};let templatePlan;try{templatePlan=this.#planTemplate({templateId:reference.templateId,pluginId:templatePluginId,overrides});}catch(cause){throw new ValidationError(`Curriculum "${request.pluginId}:${curriculum.id}" unit "${unit.id}" lesson "${lesson.id}" template "${qualified}" cannot expand: ${cause.message}`,{cause});}const identity={...sectionIdentity,templatePluginId,templateId:templatePlan.template.id,templateVersion:templatePlan.template.version,family:String(templatePlan.template.family),parameters:templatePlan.values,itemPosition:itemIndex+1},itemId=unique(itemIds,generated("curriculum-item",`${lesson.id}-${templatePlan.template.id}`,identity),`curriculum "${curriculum.id}" unit "${unit.id}" lesson "${lesson.id}" template "${qualified}"`),traceId=generated("curriculum-trace",templatePlan.template.id,{...identity,setId,sectionId,itemId});return{reference,templatePlan,templatePluginId,itemId,traceId,identity};});
            totalItems+=items.length;if(totalItems>EXERCISE_SET_LIMITS.totalItems)throw new ValidationError(`Curriculum "${request.pluginId}:${curriculum.id}" expansion reaches ${totalItems} items at unit "${unit.id}" lesson "${lesson.id}"; ExerciseSet supports at most ${EXERCISE_SET_LIMITS.totalItems} total items.`);
            planned.push({unit,lesson,sectionId,items});
        }
        const sections=planned.map(({unit,lesson,sectionId,items})=>{const sectionTrace=freezeDeep({curriculumPluginId:request.pluginId,curriculumId:curriculum.id,curriculumVersion:curriculum.version,unitId:unit.id,lessonId:lesson.id,difficulty:String(lesson.difficulty),generatedExerciseSetId:setId,generatedSectionId:sectionId});return{id:sectionId,title:lesson.title,label:unit.title,metadata:sectionTrace,items:items.map(({reference,templatePlan,templatePluginId,itemId,traceId})=>{const trace=freezeDeep({traceId,curriculumPluginId:request.pluginId,curriculumId:curriculum.id,curriculumVersion:curriculum.version,unitId:unit.id,lessonId:lesson.id,templatePluginId,templateId:templatePlan.template.id,templateVersion:templatePlan.template.version,family:String(templatePlan.template.family),parameters:templatePlan.values,generatedExerciseSetId:setId,generatedSectionId:sectionId,generatedItemId:itemId});return{id:itemId,label:reference.label??templatePlan.template.itemLabel??templatePlan.template.name,metadata:trace,application:templatePlan.application};})};});
        const exerciseSetRequest=new ExerciseSetRequest({id:setId,title:request.lessonId?sections[0].title:request.unitId?units[0].title:curriculum.title,subtitle:curriculum.description,instructions:curriculum.objective,sections});
        return new CurriculumExpansionResult({request,curriculum,exerciseSetRequest,metadata:{curriculumPluginId:request.pluginId,curriculumId:curriculum.id,curriculumVersion:curriculum.version,unitId:request.unitId,lessonId:request.lessonId,generatedExerciseSetId:setId,sectionCount:sections.length,itemCount:totalItems,deterministic:true}});
    }
}
