import { ExerciseDescriptor, PluginDescriptor, ServiceDescriptor } from "../Foundation/index.js";
import { builtInCurricula, builtInExerciseTemplates } from "./builtins.js";

export const curriculumServiceDescriptors=Object.freeze({
    templates:new ServiceDescriptor({id:"curriculum.template-catalog",name:{value:"exercise-template-catalog",displayName:"Exercise Template Catalog"},description:"Plugin-scoped immutable exercise template definitions.",layer:"application",category:"application",role:"catalog",stability:"stable",visibility:"public",capabilities:["plugin-isolation","deterministic-enumeration","immutable-snapshots"]}),
    curricula:new ServiceDescriptor({id:"curriculum.catalog",name:{value:"curriculum-catalog",displayName:"Curriculum Catalog"},description:"Plugin-scoped immutable curricula.",layer:"application",category:"application",role:"catalog",stability:"stable",visibility:"public",capabilities:["ordered-units","prerequisite-validation","deterministic-enumeration"]}),
    engine:new ServiceDescriptor({id:"curriculum.engine",name:{value:"curriculum-engine",displayName:"Curriculum Expansion Engine"},description:"Expands templates and curricula into authoritative ExerciseSet requests.",layer:"application",category:"application",role:"service",stability:"stable",visibility:"public",capabilities:["template-expansion","curriculum-expansion","exercise-set-request-output"]})
});
export const curriculumPluginDescriptor=new PluginDescriptor({id:"core.curriculum.builtins",name:{value:"curriculum-builtins",displayName:"Built-in Exercise Templates and Curricula"},description:"Immutable built-in pedagogical templates and curricula.",layer:"plugin",category:"plugin",role:"provider",stability:"stable",visibility:"public",capabilities:["exercise-templates","ordered-curricula","conventional-worksheet-expansion"],services:[{id:"curriculum.engine",kind:"service"}],extensionPoints:[{id:"curriculum.template",kind:"exercise"},{id:"curriculum.definition",kind:"exercise"}],metadata:{templateIds:builtInExerciseTemplates.map(value=>value.id),curriculumIds:builtInCurricula.map(value=>value.id)}});
export const curriculumExpansionDescriptor=new ExerciseDescriptor({id:"curriculum.expansion",name:{value:"curriculum-expansion",displayName:"Curriculum Expansion"},description:"Deterministically expands pedagogical intent into an ExerciseSetRequest.",layer:"application",category:"application",role:"service",stability:"stable",visibility:"public",capabilities:["template-expansion","heterogeneous-curricula","traceability"],plugin:{id:"core.curriculum.builtins",kind:"plugin"},inputTypes:[{id:"curriculum.expansion-request",kind:"value"}],outputTypes:[{id:"exercise.set.request",kind:"value"}],metadata:{renders:false,browserRequired:false}});
export const exerciseTemplateDescriptors=Object.freeze(builtInExerciseTemplates.map(value=>Object.freeze({id:value.id,pluginId:"core.curriculum.builtins",family:String(value.family),version:value.version,difficulty:String(value.difficulty)})));
export const builtInCurriculumDescriptors=Object.freeze(builtInCurricula.map(value=>Object.freeze({id:value.id,pluginId:"core.curriculum.builtins",version:value.version,difficulty:String(value.difficulty)})));
