import { useEffect, useId, useRef, useState } from "react";
import {
    approachPatternOptions, enclosurePatternOptions, exerciseChoicesForFamily, exerciseDirectionOptions,
    exerciseDurationOptions, exerciseFamilyOptions, exerciseTargetChoices, isAdvancedExerciseFamily,
    isProgressionExerciseFamily, isScaleExerciseFamily, isTargetExerciseFamily
} from "../exercise/workflow.js";
import { buildExerciseSetRequest, createInitialExerciseSetState, transitionExerciseSetState } from "./workflow.js";
import { useExerciseSetWorkflow } from "./useExerciseSetWorkflow.js";

const message = error => error?.message ?? error?.cause?.message ?? "The worksheet could not be generated.";
function ItemControls({ value, catalogs, onChange }) {
    const state = value.controls, scale = isScaleExerciseFamily(state.type), target = isTargetExerciseFamily(state.type), progression = isProgressionExerciseFamily(state.type), advanced = isAdvancedExerciseFamily(state.type);
    const choices = exerciseChoicesForFamily(catalogs, state.type), targets = target ? exerciseTargetChoices(catalogs, state.quality) : [];
    return <div className="worksheet-item-fields">
        <label className="field"><span>Exercise family</span><select aria-label={`Exercise family for ${value.id}`} value={state.type} onChange={event => onChange({ type: event.target.value })}>{exerciseFamilyOptions.map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>
        <label className="field"><span>Item label</span><input aria-label={`Item label for ${value.id}`} value={value.label} onChange={event => onChange(null, { label: event.target.value })} /></label>
        <label className="field"><span>All keys</span><span className="check-field"><input type="checkbox" aria-label={`All keys for ${value.id}`} checked={state.allKeys} onChange={event => onChange({ allKeys: event.target.checked })} /> Canonical order</span></label>
        {!state.allKeys && <label className="field"><span>Root</span><input aria-label={`Root for ${value.id}`} value={state.root} onChange={event => onChange({ root: event.target.value })} /></label>}
        {!progression && <label className="field"><span>{scale ? "Scale selection" : "Quality selection"}</span><select aria-label={`${scale ? "Scale pattern" : "Chord quality"} for ${value.id}`} value={scale ? state.pattern : state.quality} onChange={event => onChange({ [scale ? "pattern" : "quality"]: event.target.value })}>{choices.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>}
        {target && <label className="field"><span>Chord target</span><select aria-label={`Chord target for ${value.id}`} value={state.target} onChange={event => onChange({ target: event.target.value })}>{targets.map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>}
        {state.type === "approach-note" && <label className="field"><span>Approach pattern</span><select aria-label={`Approach pattern for ${value.id}`} value={state.approachPattern} onChange={event => onChange({ approachPattern: event.target.value })}>{approachPatternOptions.map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>}
        {state.type === "enclosure" && <label className="field"><span>Enclosure pattern</span><select aria-label={`Enclosure pattern for ${value.id}`} value={state.enclosurePattern} onChange={event => onChange({ enclosurePattern: event.target.value })}>{enclosurePatternOptions.map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>}
        {progression && <label className="field"><span>Progression</span><select aria-label={`Progression for ${value.id}`} value={state.progression} onChange={event => onChange({ progression: event.target.value })}>{choices.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>}
        {!advanced && <label className="field"><span>Direction</span><select aria-label={`Direction for ${value.id}`} value={state.direction} onChange={event => onChange({ direction: event.target.value })}>{exerciseDirectionOptions.map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>}
        {!advanced && <label className="field"><span>Octaves</span><select aria-label={`Octaves for ${value.id}`} value={state.octaves} onChange={event => onChange({ octaves: Number(event.target.value) })}><option value="1">1</option><option value="2">2</option></select></label>}
        <label className="field"><span>Starting octave</span><select aria-label={`Starting octave for ${value.id}`} value={state.startingOctave} onChange={event => onChange({ startingOctave: Number(event.target.value) })}>{[2,3,4,5,6].map(number => <option key={number}>{number}</option>)}</select></label>
        <label className="field"><span>Duration</span><select aria-label={`Duration for ${value.id}`} value={state.duration} onChange={event => onChange({ duration: event.target.value })}>{exerciseDurationOptions.map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>
        <label className="field"><span>Clef</span><select aria-label={`Clef for ${value.id}`} value={state.clef} onChange={event => onChange({ clef: event.target.value })}><option value="treble">Treble</option><option value="bass">Bass</option></select></label>
        <label className="field"><span>Time signature</span><select aria-label={`Time signature for ${value.id}`} value={`${state.beats}/${state.beatUnit}`} onChange={event => { const [beats, beatUnit] = event.target.value.split("/").map(Number); onChange({ beats, beatUnit }); }}><option value="4/4">4/4</option><option value="3/4">3/4</option><option value="2/4">2/4</option><option value="6/8">6/8</option></select></label>
        <label className="field"><span>Measures per system</span><select aria-label={`Measures per system for ${value.id}`} value={state.measuresPerSystem} onChange={event => onChange({ measuresPerSystem: Number(event.target.value) })}>{[1,2,3,4,6,8].map(number => <option key={number}>{number}</option>)}</select></label>
        <label className="field"><span>Key-signature policy</span><select aria-label={`Key-signature policy for ${value.id}`} value={state.keySignaturePolicy} onChange={event => onChange({ keySignaturePolicy: event.target.value })}><option value="none">None</option><option value="exercise-root">Exercise root</option><option value="explicit">Explicit</option></select></label>
        {state.keySignaturePolicy === "explicit" && <><label className="field"><span>Explicit key tonic</span><input aria-label={`Explicit key tonic for ${value.id}`} value={state.keySignatureTonic} onChange={event => onChange({ keySignatureTonic: event.target.value })} /></label><label className="field"><span>Explicit key mode</span><select aria-label={`Explicit key mode for ${value.id}`} value={state.keySignatureMode} onChange={event => onChange({ keySignatureMode: event.target.value })}><option value="major">Major</option><option value="minor">Minor</option></select></label></>}
    </div>;
}
function Editor({ state, catalogs, dispatch, busy }) { return <form className="worksheet-editor" aria-label="Worksheet editor" aria-busy={busy} onSubmit={event => event.preventDefault()}>
    <fieldset><legend>Worksheet details</legend><div className="worksheet-metadata">
        <label className="field"><span>Worksheet title</span><input aria-label="Worksheet title" value={state.title} onChange={event => dispatch({ type: "metadata", change: { title: event.target.value } })} /></label>
        <label className="field"><span>Subtitle</span><input aria-label="Worksheet subtitle" value={state.subtitle} onChange={event => dispatch({ type: "metadata", change: { subtitle: event.target.value } })} /></label>
        <label className="field worksheet-wide"><span>Instructions</span><textarea aria-label="Worksheet instructions" value={state.instructions} onChange={event => dispatch({ type: "metadata", change: { instructions: event.target.value } })} /></label>
    </div><button type="button" className="worksheet-add" onClick={() => dispatch({ type: "reset" })}>New Worksheet</button></fieldset>
    {state.sections.map((section, sectionIndex) => <fieldset className="worksheet-section-editor" key={section.id}><legend>Section {sectionIndex + 1}</legend>
        <div className="worksheet-section-heading"><label className="field"><span>Section title</span><input aria-label={`Title for ${section.id}`} value={section.title} onChange={event => dispatch({ type: "edit-section", sectionId: section.id, change: { title: event.target.value } })} /></label><div className="worksheet-actions"><button aria-label={`Move section up ${section.id}`} type="button" onClick={() => dispatch({ type: "move-section-up", sectionId: section.id })}>Move section up</button><button aria-label={`Move section down ${section.id}`} type="button" onClick={() => dispatch({ type: "move-section-down", sectionId: section.id })}>Move section down</button><button aria-label={`Remove section ${section.id}`} type="button" onClick={() => dispatch({ type: "remove-section", sectionId: section.id })}>Remove section</button></div></div>
        {section.items.map((item, itemIndex) => <fieldset className="worksheet-item-editor" key={item.id}><legend>Item {itemIndex + 1}</legend><ItemControls value={item} catalogs={catalogs} onChange={(controls, itemChange) => dispatch(controls ? { type: "edit-controls", sectionId: section.id, itemId: item.id, change: controls } : { type: "edit-item", sectionId: section.id, itemId: item.id, change: itemChange })} /><div className="worksheet-actions"><button aria-label={`Duplicate item ${item.id}`} type="button" onClick={() => dispatch({ type: "duplicate-item", sectionId: section.id, itemId: item.id })}>Duplicate item</button><button aria-label={`Move item up ${item.id}`} type="button" onClick={() => dispatch({ type: "move-item-up", sectionId: section.id, itemId: item.id })}>Move item up</button><button aria-label={`Move item down ${item.id}`} type="button" onClick={() => dispatch({ type: "move-item-down", sectionId: section.id, itemId: item.id })}>Move item down</button><button aria-label={`Remove item ${item.id}`} type="button" onClick={() => dispatch({ type: "remove-item", sectionId: section.id, itemId: item.id })}>Remove item</button></div></fieldset>)}
        <button type="button" className="worksheet-add" onClick={() => dispatch({ type: "add-item", sectionId: section.id })}>Add exercise item</button>
    </fieldset>)}
    <button type="button" className="worksheet-add" onClick={() => dispatch({ type: "add-section" })}>Add section</button>
</form>; }
function rowSummary(row) { const metadata = row.sourceRow.metadata; return [String(row.type).replaceAll("-", " "), String(row.root), row.quality, row.pattern, metadata.target ? `target ${metadata.target}` : null, metadata.progressionId ? `progression ${metadata.progressionId}` : null].filter(Boolean).join(" · "); }
function Worksheet({ result, stale, resultRef, id }) { if (!result) return <div className="exercise-empty"><p>Create and generate a worksheet to see it here.</p></div>; const document = result.document; return <article className="worksheet-document" ref={resultRef} tabIndex="-1" aria-labelledby={`${id}-worksheet-result-title`}><header><p className="eyebrow">Completed worksheet</p><h3 id={`${id}-worksheet-result-title`}>{document.title}</h3>{document.subtitle && <p>{document.subtitle}</p>}{document.instructions && <p>{document.instructions}</p>}{stale && <p className="stale-notice" role="status">Draft changed — generate again to refresh this worksheet.</p>}</header>{document.sections.map(section => <section key={section.id} aria-labelledby={`${id}-${section.id}-result-title`}><h4 id={`${id}-${section.id}-result-title`}>{section.title}</h4>{section.items.map(item => <article className="worksheet-result-item" key={item.id}><h5>{item.label || item.result.presentation.sections[0]?.title || `Exercise ${item.sequence}`}</h5>{item.result.presentation.sections.flatMap(value => value.rows).map(row => <section className="exercise-row" key={row.id}><h6>{row.title}</h6><p>{rowSummary(row)}</p><div className="exercise-svg-frame" role="img" aria-label={`Notation for ${row.title}`} dangerouslySetInnerHTML={{ __html: row.content }} /></section>)}</article>)}</section>)}</article>; }
export function ExerciseSetPanel({ application, catalogs }) { const id = useId(), initial = createInitialExerciseSetState(catalogs), [state, setState] = useState(initial), stateRef = useRef(initial), revision = useRef(0), resultRef = useRef(null), errorRef = useRef(null); const { workflow, submit, setInputError } = useExerciseSetWorkflow(application); const dispatch = action => { try { const current = stateRef.current, next = transitionExerciseSetState(current, action, catalogs); if (next === current) return; stateRef.current = next; revision.current += 1; setState(next); } catch (error) { setInputError(error); } }; const generate = () => { let request; try { request = buildExerciseSetRequest(stateRef.current, catalogs); } catch (error) { setInputError(error); return; } void submit(request, revision.current).catch(() => {}); }; useEffect(() => { if (workflow.result) resultRef.current?.focus(); }, [workflow.result]); const error = workflow.inputError ?? workflow.workflowError ?? workflow.presentationError; useEffect(() => { if (error) errorRef.current?.focus(); }, [error]); return <section className="exercise-set" aria-labelledby={`${id}-exercise-set-title`}><header className="exercise-practice-heading"><p className="eyebrow">v8.6 · Worksheet workflow</p><h2 id={`${id}-exercise-set-title`}>Exercise Set Worksheet</h2><p>Arrange heterogeneous exercises into one authoritative, printable practice document.</p></header><div className="worksheet-workspace"><div><Editor state={state} catalogs={catalogs} dispatch={dispatch} busy={workflow.busy} /><button type="button" className="primary-action worksheet-generate" disabled={workflow.busy} onClick={generate}>{workflow.busy ? "Generating worksheet…" : "Generate Worksheet"}</button></div><section aria-label="Worksheet result" aria-busy={workflow.busy}><p className="exercise-live" aria-live="polite" aria-atomic="true">{workflow.busy ? "Generating worksheet…" : workflow.result ? "Worksheet ready." : "Worksheet draft ready."}</p>{error && <div ref={errorRef} tabIndex="-1" className="exercise-error" role="alert"><strong>Worksheet generation failed.</strong> {message(error)}</div>}<Worksheet id={id} result={workflow.result} stale={Boolean(workflow.result) && workflow.resultRevision !== revision.current} resultRef={resultRef} /></section></div></section>; }
export default ExerciseSetPanel;
